run:
  timeout: 5m

linters-settings:
  revive:
    confidence: 0.8
    rules:
      - name: empty-block
      - name: unreachable-code
      - name: superfluous-else
  gosec:
    excludes:
      - G306
      - G115

linters:
  disable-all: true
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
