// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package accountdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyAccountManualOverride = `-- name: ApplyAccountManualOverride :exec
UPDATE account_states
SET manual_override = $1,
    state = $2,
    derivation_version = derivation_version + 1,
    updated_at = now()
WHERE pubkey = $3
`

type ApplyAccountManualOverrideParams struct {
	ManualOverride *string
	EffectiveState string
	Pubkey         string
}

func (q *Queries) ApplyAccountManualOverride(ctx context.Context, arg ApplyAccountManualOverrideParams) error {
	_, err := q.db.Exec(ctx, applyAccountManualOverride, arg.ManualOverride, arg.EffectiveState, arg.Pubkey)
	return err
}

const applyAccountStateUpdate = `-- name: ApplyAccountStateUpdate :exec

UPDATE account_states
SET derived_state = $1,
    state = $2,
    derivation_version = derivation_version + 1,
    updated_at = now()
WHERE pubkey = $3
`

type ApplyAccountStateUpdateParams struct {
	DerivedState   string
	EffectiveState string
	Pubkey         string
}

// Account-state bounded-context queries for the sqlc pilot.
//
// Scope: the single-table account_states / account_state_transitions
// statements. The multi-context ListAccountSignalsForRecompute join (into the
// trust and profile projections) is intentionally out of the pilot: it reaches
// across bounded contexts and stays hand-written in account.go.
//
// The exported Accounts methods remain the public surface and keep owning
// transaction orchestration; they call these generated statements through a
// *Queries bound to either the pool or an in-flight pgx.Tx.
func (q *Queries) ApplyAccountStateUpdate(ctx context.Context, arg ApplyAccountStateUpdateParams) error {
	_, err := q.db.Exec(ctx, applyAccountStateUpdate, arg.DerivedState, arg.EffectiveState, arg.Pubkey)
	return err
}

const countAccountStates = `-- name: CountAccountStates :many
SELECT state, COUNT(*) AS count
FROM account_states
GROUP BY state
`

type CountAccountStatesRow struct {
	State string
	Count int64
}

func (q *Queries) CountAccountStates(ctx context.Context) ([]CountAccountStatesRow, error) {
	rows, err := q.db.Query(ctx, countAccountStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAccountStatesRow{}
	for rows.Next() {
		var i CountAccountStatesRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountState = `-- name: GetAccountState :one
SELECT pubkey, state, derived_state, manual_override, first_seen_at, first_tracked_at,
       last_observed_at, observed_count, last_hydrated_at, last_successful_hydration_at,
       oldest_known_note_at, newest_known_note_at, engagement_last_checked_at,
       coverage_window_days, updated_at, derivation_version
FROM account_states
WHERE pubkey = $1
`

func (q *Queries) GetAccountState(ctx context.Context, pubkey string) (AccountState, error) {
	row := q.db.QueryRow(ctx, getAccountState, pubkey)
	var i AccountState
	err := row.Scan(
		&i.Pubkey,
		&i.State,
		&i.DerivedState,
		&i.ManualOverride,
		&i.FirstSeenAt,
		&i.FirstTrackedAt,
		&i.LastObservedAt,
		&i.ObservedCount,
		&i.LastHydratedAt,
		&i.LastSuccessfulHydrationAt,
		&i.OldestKnownNoteAt,
		&i.NewestKnownNoteAt,
		&i.EngagementLastCheckedAt,
		&i.CoverageWindowDays,
		&i.UpdatedAt,
		&i.DerivationVersion,
	)
	return i, err
}

const getAccountStateForOverride = `-- name: GetAccountStateForOverride :one
SELECT state, derived_state
FROM account_states
WHERE pubkey = $1
`

type GetAccountStateForOverrideRow struct {
	State        string
	DerivedState string
}

func (q *Queries) GetAccountStateForOverride(ctx context.Context, pubkey string) (GetAccountStateForOverrideRow, error) {
	row := q.db.QueryRow(ctx, getAccountStateForOverride, pubkey)
	var i GetAccountStateForOverrideRow
	err := row.Scan(&i.State, &i.DerivedState)
	return i, err
}

const getAccountStateForPromote = `-- name: GetAccountStateForPromote :one
SELECT state, (manual_override IS NOT NULL)::bool AS has_override
FROM account_states
WHERE pubkey = $1
`

type GetAccountStateForPromoteRow struct {
	State       string
	HasOverride bool
}

func (q *Queries) GetAccountStateForPromote(ctx context.Context, pubkey string) (GetAccountStateForPromoteRow, error) {
	row := q.db.QueryRow(ctx, getAccountStateForPromote, pubkey)
	var i GetAccountStateForPromoteRow
	err := row.Scan(&i.State, &i.HasOverride)
	return i, err
}

const insertAccountStateTransition = `-- name: InsertAccountStateTransition :exec
INSERT INTO account_state_transitions (pubkey, from_state, to_state, reason, source)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAccountStateTransitionParams struct {
	Pubkey    string
	FromState string
	ToState   string
	Reason    *string
	Source    string
}

func (q *Queries) InsertAccountStateTransition(ctx context.Context, arg InsertAccountStateTransitionParams) error {
	_, err := q.db.Exec(ctx, insertAccountStateTransition,
		arg.Pubkey,
		arg.FromState,
		arg.ToState,
		arg.Reason,
		arg.Source,
	)
	return err
}

const insertTrackedAccountState = `-- name: InsertTrackedAccountState :exec
INSERT INTO account_states (pubkey, state, derived_state, first_seen_at, first_tracked_at, last_observed_at, updated_at)
VALUES ($1, 'tracked', 'unknown', now(), now(), now(), now())
ON CONFLICT (pubkey) DO NOTHING
`

func (q *Queries) InsertTrackedAccountState(ctx context.Context, pubkey string) error {
	_, err := q.db.Exec(ctx, insertTrackedAccountState, pubkey)
	return err
}

const insertUnknownAccountState = `-- name: InsertUnknownAccountState :exec
INSERT INTO account_states (pubkey, state, derived_state, first_seen_at, last_observed_at, updated_at)
VALUES ($1, 'unknown', 'unknown', now(), now(), now())
ON CONFLICT (pubkey) DO NOTHING
`

func (q *Queries) InsertUnknownAccountState(ctx context.Context, pubkey string) error {
	_, err := q.db.Exec(ctx, insertUnknownAccountState, pubkey)
	return err
}

const loadPubkeysByStates = `-- name: LoadPubkeysByStates :many
SELECT pubkey
FROM account_states
WHERE state = ANY($1::text[])
`

func (q *Queries) LoadPubkeysByStates(ctx context.Context, states []string) ([]string, error) {
	rows, err := q.db.Query(ctx, loadPubkeysByStates, states)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var pubkey string
		if err := rows.Scan(&pubkey); err != nil {
			return nil, err
		}
		items = append(items, pubkey)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteAccountToTracked = `-- name: PromoteAccountToTracked :exec
UPDATE account_states
SET first_tracked_at = COALESCE(first_tracked_at, now()),
    state = CASE
        WHEN manual_override IS NOT NULL THEN state
        WHEN state IN ('tracked','strategic') THEN state
        ELSE 'tracked'
    END,
    derivation_version = derivation_version + 1,
    updated_at = now()
WHERE pubkey = $1
`

func (q *Queries) PromoteAccountToTracked(ctx context.Context, pubkey string) error {
	_, err := q.db.Exec(ctx, promoteAccountToTracked, pubkey)
	return err
}

const purgeAccountStateTransitionsOlderThan = `-- name: PurgeAccountStateTransitionsOlderThan :execrows
DELETE FROM account_state_transitions
WHERE id IN (
    SELECT t.id FROM account_state_transitions t
    WHERE t.created_at < $1
    ORDER BY t.id
    LIMIT $2
)
`

type PurgeAccountStateTransitionsOlderThanParams struct {
	Cutoff   pgtype.Timestamptz
	RowLimit int32
}

func (q *Queries) PurgeAccountStateTransitionsOlderThan(ctx context.Context, arg PurgeAccountStateTransitionsOlderThanParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAccountStateTransitionsOlderThan, arg.Cutoff, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccountCoverage = `-- name: UpdateAccountCoverage :exec
UPDATE account_states
SET last_hydrated_at = COALESCE($1, last_hydrated_at),
    last_successful_hydration_at = COALESCE($2, last_successful_hydration_at),
    oldest_known_note_at = COALESCE($3, oldest_known_note_at),
    newest_known_note_at = COALESCE($4, newest_known_note_at),
    engagement_last_checked_at = COALESCE($5, engagement_last_checked_at),
    coverage_window_days = COALESCE($6, coverage_window_days),
    updated_at = now()
WHERE pubkey = $7
`

type UpdateAccountCoverageParams struct {
	LastHydratedAt            pgtype.Timestamptz
	LastSuccessfulHydrationAt pgtype.Timestamptz
	OldestKnownNoteAt         pgtype.Timestamptz
	NewestKnownNoteAt         pgtype.Timestamptz
	EngagementLastCheckedAt   pgtype.Timestamptz
	CoverageWindowDays        *int32
	Pubkey                    string
}

func (q *Queries) UpdateAccountCoverage(ctx context.Context, arg UpdateAccountCoverageParams) error {
	_, err := q.db.Exec(ctx, updateAccountCoverage,
		arg.LastHydratedAt,
		arg.LastSuccessfulHydrationAt,
		arg.OldestKnownNoteAt,
		arg.NewestKnownNoteAt,
		arg.EngagementLastCheckedAt,
		arg.CoverageWindowDays,
		arg.Pubkey,
	)
	return err
}
