// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accountdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountState struct {
	Pubkey                    string
	State                     string
	DerivedState              string
	ManualOverride            *string
	FirstSeenAt               pgtype.Timestamptz
	FirstTrackedAt            pgtype.Timestamptz
	LastObservedAt            pgtype.Timestamptz
	ObservedCount             int64
	LastHydratedAt            pgtype.Timestamptz
	LastSuccessfulHydrationAt pgtype.Timestamptz
	OldestKnownNoteAt         pgtype.Timestamptz
	NewestKnownNoteAt         pgtype.Timestamptz
	EngagementLastCheckedAt   pgtype.Timestamptz
	CoverageWindowDays        *int32
	UpdatedAt                 pgtype.Timestamptz
	DerivationVersion         int64
}

type AccountStateTransition struct {
	ID        int64
	Pubkey    string
	FromState string
	ToState   string
	Reason    *string
	Source    string
	CreatedAt pgtype.Timestamptz
}
