// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accountdb

import (
	"context"
)

type Querier interface {
	ApplyAccountManualOverride(ctx context.Context, arg ApplyAccountManualOverrideParams) error
	// Account-state bounded-context queries for the sqlc pilot.
	//
	// Scope: the single-table account_states / account_state_transitions
	// statements. The multi-context ListAccountSignalsForRecompute join (into the
	// trust and profile projections) is intentionally out of the pilot: it reaches
	// across bounded contexts and stays hand-written in account.go.
	//
	// The exported Accounts methods remain the public surface and keep owning
	// transaction orchestration; they call these generated statements through a
	// *Queries bound to either the pool or an in-flight pgx.Tx.
	ApplyAccountStateUpdate(ctx context.Context, arg ApplyAccountStateUpdateParams) error
	CountAccountStates(ctx context.Context) ([]CountAccountStatesRow, error)
	GetAccountState(ctx context.Context, pubkey string) (AccountState, error)
	GetAccountStateForOverride(ctx context.Context, pubkey string) (GetAccountStateForOverrideRow, error)
	GetAccountStateForPromote(ctx context.Context, pubkey string) (GetAccountStateForPromoteRow, error)
	InsertAccountStateTransition(ctx context.Context, arg InsertAccountStateTransitionParams) error
	InsertTrackedAccountState(ctx context.Context, pubkey string) error
	InsertUnknownAccountState(ctx context.Context, pubkey string) error
	LoadPubkeysByStates(ctx context.Context, states []string) ([]string, error)
	PromoteAccountToTracked(ctx context.Context, pubkey string) error
	PurgeAccountStateTransitionsOlderThan(ctx context.Context, arg PurgeAccountStateTransitionsOlderThanParams) (int64, error)
	UpdateAccountCoverage(ctx context.Context, arg UpdateAccountCoverageParams) error
}

var _ Querier = (*Queries)(nil)
