ALTER TABLE note_discovery_stats
    ADD COLUMN IF NOT EXISTS has_image BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS has_video BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS has_link BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS has_article BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS attachment_count INTEGER NOT NULL DEFAULT 0 CHECK (attachment_count >= 0);

ALTER TABLE author_media_mix_stats
    ADD COLUMN IF NOT EXISTS with_article_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_attachment_count BIGINT NOT NULL DEFAULT 0;
