// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package retentiondb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountState struct {
	Pubkey                    string
	State                     string
	DerivedState              string
	ManualOverride            pgtype.Text
	FirstSeenAt               pgtype.Timestamptz
	FirstTrackedAt            pgtype.Timestamptz
	LastObservedAt            pgtype.Timestamptz
	ObservedCount             int64
	LastHydratedAt            pgtype.Timestamptz
	LastSuccessfulHydrationAt pgtype.Timestamptz
	OldestKnownNoteAt         pgtype.Timestamptz
	NewestKnownNoteAt         pgtype.Timestamptz
	EngagementLastCheckedAt   pgtype.Timestamptz
	CoverageWindowDays        pgtype.Int4
	UpdatedAt                 pgtype.Timestamptz
	DerivationVersion         int64
}

type AccountStateTransition struct {
	ID        int64
	Pubkey    string
	FromState string
	ToState   string
	Reason    pgtype.Text
	Source    string
	CreatedAt pgtype.Timestamptz
}

type AppliedStatDelta struct {
	EventID    string
	Projection string
	AppliedAt  pgtype.Timestamptz
}

type AuthorActivityDaily struct {
	Pubkey             string
	ActivityDate       pgtype.Date
	PostCount          int64
	NoteCount          int64
	ReplyCount         int64
	EngagementReceived int64
	EngagementGiven    int64
	DerivationVersion  int32
	UpdatedAt          pgtype.Timestamptz
	ZapMsatsReceived   int64
}

type AuthorActivityWindow struct {
	Pubkey             string
	WindowDays         int32
	DayOfWeek          int16
	HourOfDay          int16
	EngagementReceived int64
	ReplyReceived      int64
	ReactionReceived   int64
	RepostReceived     int64
	ZapReceived        int64
	DerivationVersion  int32
	UpdatedAt          pgtype.Timestamptz
}

type AuthorEngagementStat struct {
	Pubkey                   string
	WindowDays               int32
	PostCount                int64
	NoteCount                int64
	ReplyCount               int64
	ActiveDays               int32
	EngagementReceived       int64
	EngagementGiven          int64
	CadencePostsPerDay       float64
	CadencePostsPerActiveDay float64
	RecentActivityAt         pgtype.Int8
	DerivationVersion        int32
	UpdatedAt                pgtype.Timestamptz
}

type AuthorHashtagDaily struct {
	Pubkey            string
	ActivityDate      pgtype.Date
	Hashtag           string
	UsageCount        int64
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type AuthorHourlyActivity struct {
	Pubkey             string
	ActivityDate       pgtype.Date
	DayOfWeek          int16
	HourOfDay          int16
	PostCount          int64
	NoteCount          int64
	ReplyCount         int64
	EngagementReceived int64
	ReplyReceived      int64
	ReactionReceived   int64
	RepostReceived     int64
	ZapReceived        int64
	DerivationVersion  int32
	UpdatedAt          pgtype.Timestamptz
	ZapMsatsReceived   int64
	AuthoredEventCount int64
}

type AuthorMediaDaily struct {
	Pubkey               string
	ActivityDate         pgtype.Date
	TotalPosts           int64
	WithImageCount       int64
	WithVideoCount       int64
	WithLinkCount        int64
	WithArticleCount     int64
	TextOnlyCount        int64
	TotalAttachmentCount int64
	DerivationVersion    int32
	UpdatedAt            pgtype.Timestamptz
}

type AuthorMediaMixStat struct {
	Pubkey               string
	WindowDays           int32
	TotalPosts           int64
	WithImageCount       int64
	WithVideoCount       int64
	WithLinkCount        int64
	TextOnlyCount        int64
	DerivationVersion    int32
	UpdatedAt            pgtype.Timestamptz
	WithArticleCount     int64
	TotalAttachmentCount int64
}

type AuthorPostingPattern struct {
	Pubkey            string
	WindowDays        int32
	DayOfWeek         int16
	HourOfDay         int16
	PostCount         int64
	NoteCount         int64
	ReplyCount        int64
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type AuthorRecentEvent struct {
	AuthorPubkey      string
	EventID           string
	CreatedAt         int64
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}

type AuthorTopicStat struct {
	Pubkey            string
	WindowDays        int32
	Hashtag           string
	UsageCount        int64
	ActiveDays        int32
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type ContactListsLatest struct {
	Pubkey            string
	EventID           string
	CreatedAt         int64
	ContactsJson      []byte
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type CuratedCreatorPaidTier struct {
	Pubkey    string
	TierID    string
	Title     string
	PriceSats int64
}

type CuratedFeaturedAuthor struct {
	Pubkey string
	Rank   int32
}

type CuratedReadsTopic struct {
	Topic string
	Rank  int32
}

type CuratedRecommendedRead struct {
	EventID string
	Title   string
	Url     string
	Rank    int32
}

type DeletionEvent struct {
	EventID           string
	DeleterPubkey     string
	TargetEventID     string
	CreatedAt         int64
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}

type DerivationActiveVersion struct {
	DerivationName string
	ActiveVersion  int32
	TargetVersion  int32
	Description    string
	UpdatedAt      pgtype.Timestamptz
}

type DerivationVersion struct {
	DerivationName string
	Version        int32
	Description    string
	UpdatedAt      pgtype.Timestamptz
}

type DmReadCursor struct {
	UserPubkey        string
	PeerPubkey        string
	LastReadCreatedAt int64
	LastReadEventID   string
	UpdatedAt         pgtype.Timestamptz
}

type DmUnreadCount struct {
	ReceiverPubkey string
	SenderPubkey   string
	Cnt            int64
	LatestAt       int64
	LatestEventID  string
	UpdatedAt      pgtype.Timestamptz
}

type Event struct {
	ID          string
	Pubkey      string
	CreatedAt   int64
	Kind        int32
	Sig         string
	Content     string
	RawJson     []byte
	FirstSeenAt pgtype.Timestamptz
	InsertedAt  pgtype.Timestamptz
	ContentTsv  interface{}
}

type EventHashtag struct {
	EventID           string
	AuthorPubkey      string
	CreatedAt         int64
	Hashtag           string
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}

type EventReference struct {
	SourceEventID     string
	ReferencedEventID string
	Relation          string
	TagIndex          int32
	RelayHint         pgtype.Text
	Marker            pgtype.Text
	DerivationVersion int32
	DerivedAt         pgtype.Timestamptz
}

type EventRelay struct {
	EventID  string
	RelayUrl string
	SeenAt   pgtype.Timestamptz
	Pubkey   string
}

type EventTag struct {
	EventID    string
	TagName    string
	TagIndex   int32
	ValueIndex int32
	Value      string
	RawValues  []byte
}

type EventUrl struct {
	EventID      string
	AuthorPubkey string
	CreatedAt    int64
	Url          string
	// Normalized hostname observed in the event URL, retained for event-level provenance.
	Domain            string
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
	// Backend-owned discovery identity used for domain aggregation and lookup.
	CanonicalDomain string
}

type FollowerEdge struct {
	FollowedPubkey       string
	FollowerPubkey       string
	SourceEventID        string
	ContactListCreatedAt int64
	DerivationVersion    int32
	UpdatedAt            pgtype.Timestamptz
}

type FollowerGainsDaily struct {
	Pubkey            string
	ActivityDate      pgtype.Date
	Gained            int64
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type IngestCheckpoint struct {
	RelayUrl           string
	Mode               string
	FilterGroup        string
	Since              pgtype.Int8
	Until              pgtype.Int8
	Cursor             pgtype.Text
	EoseSeenAt         pgtype.Timestamptz
	Status             string
	UpdatedAt          pgtype.Timestamptz
	LastEventID        pgtype.Text
	LastProgressAt     pgtype.Timestamptz
	LastError          pgtype.Text
	LastConnectedAt    pgtype.Timestamptz
	LastDisconnectedAt pgtype.Timestamptz
	LastErrorAt        pgtype.Timestamptz
	ReconnectCount     int32
}

type IngestPubkeyFrontier struct {
	Pubkey         string
	SourceRunID    int64
	TrustRank      int64
	TrustScore     float64
	State          string
	FirstSeenAt    pgtype.Timestamptz
	LastSelectedAt pgtype.Timestamptz
	LastFetchedAt  pgtype.Timestamptz
	NextEligibleAt pgtype.Timestamptz
	FetchAttempts  int32
	SuccessCount   int32
	LastError      pgtype.Text
	LastErrorAt    pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type InvalidEvent struct {
	ID           int64
	SourceRelay  pgtype.Text
	ErrorCode    string
	ErrorMessage string
	RawPayload   []byte
	SeenAt       pgtype.Timestamptz
}

type Job struct {
	ID             int64
	JobType        string
	Payload        []byte
	IdempotencyKey pgtype.Text
	Status         string
	Attempts       int32
	MaxAttempts    int32
	RunAfter       pgtype.Timestamptz
	LockedAt       pgtype.Timestamptz
	LockedBy       pgtype.Text
	LastError      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	WorkerPool     string
	FinishedAt     pgtype.Timestamptz
}

type NoteDiscoveryStat struct {
	EventID            string
	AuthorPubkey       string
	CreatedAt          int64
	ReplyCount         int64
	RepostCount        int64
	ReactionCount      int64
	ZapCount           int64
	ZapMsats           int64
	Score24h           float64
	Score7d            float64
	LastScoredAt       pgtype.Timestamptz
	DerivationVersion  int32
	ProjectedAt        pgtype.Timestamptz
	HasImage           bool
	HasVideo           bool
	HasLink            bool
	HasArticle         bool
	AttachmentCount    int32
	PrimaryLanguage    pgtype.Text
	LanguageConfidence pgtype.Float8
}

type PendingAuthorAnalyticsRecompute struct {
	Pubkey     string
	MarkedAt   pgtype.Timestamptz
	ClaimedAt  pgtype.Timestamptz
	ClaimToken pgtype.UUID
}

type PendingMeilisearchSync struct {
	EventID  string
	MarkedAt pgtype.Timestamptz
}

type PendingProfileStatsRecompute struct {
	Pubkey     string
	MarkedAt   pgtype.Timestamptz
	ClaimedAt  pgtype.Timestamptz
	ClaimToken pgtype.UUID
}

type ProfileDiscoveryRecentActivity struct {
	Pubkey           string
	RecentActivityAt int64
	UpdatedAt        pgtype.Timestamptz
}

type ProfileDiscoveryStat struct {
	Pubkey                   string
	Score24h                 float64
	Score7d                  float64
	RisingScore24h           float64
	RisingScore7d            float64
	RecentPostCount          int64
	RecentReplyCount         int64
	RecentEngagementReceived int64
	RecentZapVolumeMsats     int64
	RecentActiveDays         int32
	RecentActivityAt         pgtype.Int8
	LastScoredAt             pgtype.Timestamptz
	DerivationVersion        int32
	ProjectedAt              pgtype.Timestamptz
}

type ProfilePublicStat struct {
	Pubkey            string
	FollowerCount     int64
	FollowingCount    int64
	NoteCount         int64
	ReplyCount        int64
	RecentActivityAt  pgtype.Int8
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type ProfilesLatest struct {
	Pubkey            string
	MetadataEventID   string
	MetadataCreatedAt int64
	ProfileJson       []byte
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
	Name              pgtype.Text
	DisplayName       pgtype.Text
	About             pgtype.Text
	Nip05             pgtype.Text
	SearchTsv         interface{}
}

type ProjectionRebuildRun struct {
	ID                  int64
	DerivationName      string
	TargetVersion       int32
	ScopeType           string
	ScopeEventID        pgtype.Text
	ScopePubkey         pgtype.Text
	ScopeStartCreatedAt pgtype.Int8
	ScopeEndCreatedAt   pgtype.Int8
	Status              string
	JobID               pgtype.Int8
	Attempts            int32
	StartedAt           pgtype.Timestamptz
	FinishedAt          pgtype.Timestamptz
	LastError           pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type ReactionCount struct {
	EventID           string
	Count             int64
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type ReactionCountContribution struct {
	SourceEventID     string
	TargetEventID     string
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}

type ReactionEvent struct {
	EventID           string
	TargetEventID     string
	ReactorPubkey     string
	Content           string
	CreatedAt         int64
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}

type RelatedProfile struct {
	FocalPubkey          string
	RelatedPubkey        string
	TopicOverlap         int64
	ReplyAdjacency       int64
	InteractionAdjacency int64
	QuoteRepostAdjacency int64
	Reasons              []string
	Score                int64
	UpdatedAt            pgtype.Timestamptz
}

type RelayDesiredSet struct {
	ID            int64
	PublishedAt   pgtype.Timestamptz
	RelayUrlsJson []byte
	Source        string
	Notes         pgtype.Text
}

type RelayListsLatest struct {
	Pubkey            string
	EventID           string
	CreatedAt         int64
	RelaysJson        []byte
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type RelayProbeObservation struct {
	ID                     int64
	UrlKey                 string
	ProbedAt               pgtype.Timestamptz
	ConnectOk              bool
	SubscribeOk            bool
	EoseOk                 bool
	ConnectLatencyMs       pgtype.Float8
	EoseLatencyMs          pgtype.Float8
	ErrorCode              pgtype.Text
	ErrorTextShort         pgtype.Text
	SampleYieldCount       pgtype.Int4
	SampleDuplicateRatio   pgtype.Float8
	CapabilitySnapshotJson []byte
}

type RelayRegistry struct {
	UrlKey                string
	NormalizedUrl         string
	DiscoveredAt          pgtype.Timestamptz
	LastSeenAt            pgtype.Timestamptz
	SourceSeed            bool
	SourceUserList        bool
	SourceManual          bool
	ManualPolicy          string
	AdmissionState        string
	Score                 float64
	DistinctUserRefCount  int32
	WeightedUserRefScore  float64
	LastProbeAt           pgtype.Timestamptz
	LastProbeStatus       pgtype.Text
	LastConnectOk         pgtype.Bool
	LastSubscribeOk       pgtype.Bool
	LastEoseOk            pgtype.Bool
	AvgConnectLatencyMs   pgtype.Float8
	AvgEoseLatencyMs      pgtype.Float8
	ProbeFailRate         float64
	YieldScore            float64
	DuplicateRatio        float64
	ScoreComponentsJson   []byte
	CapabilitySummaryJson []byte
	NotesJson             []byte
	UpdatedAt             pgtype.Timestamptz
}

// Generic homepage-window snapshot store keyed by snapshot_label. Despite the historical name, hosts snapshots for relay summary, note volume / active authors, top languages, and top hashtags. Refreshed every few minutes by derivation.RefreshRelayWindowSnapshots — see internal/derivation/projection_relay_window_snapshots.go.
type RelayWindowSnapshot struct {
	SnapshotLabel string
	Payload       []byte
	ComputedAt    pgtype.Timestamptz
}

type ReplaceableState struct {
	Pubkey            string
	Kind              int32
	DTag              string
	EventID           string
	CreatedAt         int64
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type ReplyCount struct {
	EventID           string
	Count             int64
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type ReplyCountContribution struct {
	SourceEventID     string
	TargetEventID     string
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}

type RepostCount struct {
	EventID           string
	Count             int64
	DerivationVersion int32
	UpdatedAt         pgtype.Timestamptz
}

type RepostCountContribution struct {
	SourceEventID     string
	TargetEventID     string
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}

type RepostEvent struct {
	EventID           string
	TargetEventID     string
	ReposterPubkey    string
	Quote             pgtype.Text
	CreatedAt         int64
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}

type SchemaMigrationsAudit struct {
	MigrationID string
	AppliedAt   pgtype.Timestamptz
	AppVersion  pgtype.Text
	Checksum    string
}

type SearchDocument struct {
	EntityType     string
	EntityID       string
	Title          string
	Body           string
	Aliases        []string
	IdentityTokens []string
	Freshness      pgtype.Timestamptz
	Popularity     float64
	TrustScore     pgtype.Float8
	UpdatedAt      pgtype.Timestamptz
	SearchTsv      interface{}
}

// Hourly append-only history of rolling 24-hour public discovery metrics, written by RefreshRelayWindowSnapshots.
type StatsSnapshotHistory struct {
	BucketStart   pgtype.Timestamptz
	ComputedAt    pgtype.Timestamptz
	NoteVolume    int64
	ActiveAuthors int64
	RelayEvents   int64
}

type StoragePressureState struct {
	ID            bool
	Level         int32
	Ratio         float64
	DatabaseBytes int64
	CapacityBytes int64
	ComputedAt    pgtype.Timestamptz
}

type ThreadEdge struct {
	ChildEventID      string
	ChildCreatedAt    int64
	ParentEventID     string
	RootEventID       pgtype.Text
	ParentMissing     bool
	RootMissing       bool
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}

type ThreadSummary struct {
	RootEventID       string
	ReplyCount        int64
	ParticipantCount  int32
	MaxDepth          int32
	LastActivityAt    int64
	Replies24h        int64
	Replies7d         int64
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}

type TrustGraphSnapshot struct {
	Pubkey      string
	MinHops     int32
	IsSeed      bool
	SourceRunID pgtype.Int8
	RefreshedAt pgtype.Timestamptz
}

type TrustRelaySuggestion struct {
	RelayUrl                string
	WeightedScore           float64
	SupportingPubkeysCount  int32
	SupportingPubkeysSample []byte
	SourceRunID             pgtype.Int8
	SourceComputedAt        pgtype.Timestamptz
	FirstSeenAt             pgtype.Timestamptz
	LastSeenAt              pgtype.Timestamptz
	LastPromotedAt          pgtype.Timestamptz
	IsRecommended           bool
	UpdatedAt               pgtype.Timestamptz
}

type TrustRun struct {
	ID                      int64
	DerivationName          string
	TargetVersion           int32
	Status                  string
	JobID                   pgtype.Int8
	Attempts                int32
	InputFollowerEdgesCount int64
	ScoreRowsPublished      int64
	RedisSnapshotRef        pgtype.Text
	StartedAt               pgtype.Timestamptz
	FinishedAt              pgtype.Timestamptz
	LastError               pgtype.Text
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	CurrentPhase            pgtype.Text
	SyncJobID               pgtype.Int8
	ComputeJobID            pgtype.Int8
	PromoteJobID            pgtype.Int8
	PhaseStartedAt          pgtype.Timestamptz
	PhaseFinishedAt         pgtype.Timestamptz
	PhaseLastError          pgtype.Text
}

type TrustScoresGlobal struct {
	Pubkey         string
	Score          float64
	Rank           int64
	RunID          int64
	DerivationName string
	TargetVersion  int32
	ComputedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type TrustScoresGlobalStage struct {
	RunID          int64
	Pubkey         string
	Score          float64
	Rank           int64
	DerivationName string
	TargetVersion  int32
	ComputedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type TrustSeed struct {
	Pubkey    string
	IsActive  bool
	Note      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TrustedDiscoveryProjectionState struct {
	ProjectionName           string
	TrustSnapshotRefreshedAt pgtype.Timestamptz
	RefreshedAt              pgtype.Timestamptz
	DerivationVersion        int32
}

type TrustedNoteDiscoveryCandidate struct {
	EventID                  string
	AuthorPubkey             string
	MinHops                  pgtype.Int4
	TrustScore               pgtype.Float8
	SourceRunID              pgtype.Int8
	TrustSnapshotRefreshedAt pgtype.Timestamptz
	DerivationVersion        int32
	ProjectedAt              pgtype.Timestamptz
}

type TrustedProfileDiscoveryCandidate struct {
	Pubkey                   string
	MinHops                  pgtype.Int4
	TrustScore               pgtype.Float8
	SourceRunID              pgtype.Int8
	TrustSnapshotRefreshedAt pgtype.Timestamptz
	DerivationVersion        int32
	ProjectedAt              pgtype.Timestamptz
}

type UnresolvedThreadReference struct {
	SourceEventID     string
	MissingEventID    string
	Relation          string
	DerivationVersion int32
	DetectedAt        pgtype.Timestamptz
}

type ZapReceipt struct {
	ZapReceiptID      string
	CreatedAt         int64
	EventID           pgtype.Text
	SenderPubkey      string
	ReceiverPubkey    pgtype.Text
	AmountSats        int64
	DerivationVersion int32
	ProjectedAt       pgtype.Timestamptz
}
