// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package retentiondb

import (
	"context"
)

type Querier interface {
	GroomSearchDocumentsPrune(ctx context.Context, rowLimit int32) (int64, error)
	GroomSearchDocumentsTrim(ctx context.Context, arg GroomSearchDocumentsTrimParams) (int64, error)
	PruneAuthorRecentEventsByAge(ctx context.Context, arg PruneAuthorRecentEventsByAgeParams) (int64, error)
	PruneAuthorRecentEventsByCap(ctx context.Context, arg PruneAuthorRecentEventsByCapParams) (int64, error)
	// Static retention sweeps for the retention bounded context. Every statement
	// is a bounded DELETE/UPDATE that returns the number of affected rows
	// (:execrows). The hand-written wrappers in internal/store/retention own
	// validation, metrics, and transaction shape; these are pure SQL plumbing.
	PurgeExpiredEngagementEvents(ctx context.Context, arg PurgeExpiredEngagementEventsParams) (int64, error)
	PurgeIdleAccountStates(ctx context.Context, arg PurgeIdleAccountStatesParams) (int64, error)
	PurgeProcessedDeletionEvents(ctx context.Context, arg PurgeProcessedDeletionEventsParams) (int64, error)
	PurgeStaleEventRelays(ctx context.Context, arg PurgeStaleEventRelaysParams) (int64, error)
	PurgeStaleTrustedNoteDiscoveryCandidates(ctx context.Context, arg PurgeStaleTrustedNoteDiscoveryCandidatesParams) (int64, error)
	PurgeStaleTrustedProfileDiscoveryCandidates(ctx context.Context, arg PurgeStaleTrustedProfileDiscoveryCandidatesParams) (int64, error)
	PurgeSupersededReplaceableEvents(ctx context.Context, arg PurgeSupersededReplaceableEventsParams) (int64, error)
	PurgeUntrustedAuthorEvents(ctx context.Context, arg PurgeUntrustedAuthorEventsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
