// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package retentiondb

import (
	"context"
)

type Querier interface {
	// Deletes an explicit, already-decided set of event ids. Used after
	// SelectExpiredEngagementEventCandidates / SelectUntrustedAuthorEventCandidates
	// so the same candidate set that had its incremental stats reversed is the
	// exact set deleted (no re-evaluating the candidate predicate a second time
	// against a possibly-changed table state).
	DeleteEventsByID(ctx context.Context, ids []string) (int64, error)
	GroomSearchDocumentsPrune(ctx context.Context, rowLimit int32) (int64, error)
	GroomSearchDocumentsTrim(ctx context.Context, arg GroomSearchDocumentsTrimParams) (int64, error)
	PruneAuthorRecentEventsByAge(ctx context.Context, arg PruneAuthorRecentEventsByAgeParams) (int64, error)
	PruneAuthorRecentEventsByCap(ctx context.Context, arg PruneAuthorRecentEventsByCapParams) (int64, error)
	// Drop event_tags rows that the ingest allowlist would no longer write.
	// Matches internal/eventtags.ShouldPersist:
	//   * tag_name outside @allowed_tag_names
	//   * kind-3 contact-list p-tags
	//   * kind-10002 relay-list r-tags
	// events.raw_json remains the source of truth; this only shrinks the
	// derived join index. Batched via LIMIT so the worker catchup loop can
	// drain hundreds of millions of rows without a single long transaction.
	PruneFilteredEventTags(ctx context.Context, arg PruneFilteredEventTagsParams) (int64, error)
	// Deletes applied_stat_deltas ledger rows whose source event no longer
	// exists in events. This is the only condition under which a ledger row is
	// guaranteed to serve no further purpose: as long as the event exists,
	// projection_incremental_stats.go's unclaimStatDeltaTx path may still need
	// the row to gate a future decrement (see reverseAndDeleteTx in retention.go,
	// which atomically reverses deltas and deletes the event together, itself
	// deleting the ledger rows it unclaims). Once the event row is gone — via
	// that reversal-aware path, or via a purge that never touched incremental
	// stats (PurgeSupersededReplaceableEvents, PurgeProcessedDeletionEvents) —
	// any ledger row still referencing that event_id is a pure orphan.
	//
	// applied_before is a conservative grace buffer on top of the orphan check
	// (not itself a correctness requirement) that keeps freshly-inserted rows
	// out of the scan and bounds it via idx_applied_stat_deltas_applied_at.
	PruneOrphanedAppliedStatDeltas(ctx context.Context, arg PruneOrphanedAppliedStatDeltasParams) (int64, error)
	// Static retention sweeps for the retention bounded context. Every statement
	// is a bounded DELETE/UPDATE that returns the number of affected rows
	// (:execrows). The hand-written wrappers in internal/store/retention own
	// validation, metrics, and transaction shape; these are pure SQL plumbing.
	PurgeExpiredEngagementEvents(ctx context.Context, arg PurgeExpiredEngagementEventsParams) (int64, error)
	PurgeIdleAccountStates(ctx context.Context, arg PurgeIdleAccountStatesParams) (int64, error)
	PurgeProcessedDeletionEvents(ctx context.Context, arg PurgeProcessedDeletionEventsParams) (int64, error)
	PurgeStaleEventRelays(ctx context.Context, arg PurgeStaleEventRelaysParams) (int64, error)
	PurgeStaleTrustedNoteDiscoveryCandidates(ctx context.Context, arg PurgeStaleTrustedNoteDiscoveryCandidatesParams) (int64, error)
	PurgeStaleTrustedProfileDiscoveryCandidates(ctx context.Context, arg PurgeStaleTrustedProfileDiscoveryCandidatesParams) (int64, error)
	PurgeSupersededReplaceableEvents(ctx context.Context, arg PurgeSupersededReplaceableEventsParams) (int64, error)
	PurgeUntrustedAuthorEventHashtags(ctx context.Context, rowLimit int32) (int64, error)
	PurgeUntrustedAuthorEventURLs(ctx context.Context, rowLimit int32) (int64, error)
	PurgeUntrustedAuthorEvents(ctx context.Context, arg PurgeUntrustedAuthorEventsParams) (int64, error)
	// Read-only counterpart to PurgeExpiredEngagementEvents' candidates CTE,
	// used by the Go wrapper to reverse incremental author-stat deltas for each
	// candidate before deleting it (see internal/store/retention/events_retention.go).
	SelectExpiredEngagementEventCandidates(ctx context.Context, arg SelectExpiredEngagementEventCandidatesParams) ([]string, error)
	// Read-only counterpart to PurgeUntrustedAuthorEvents' candidates CTE, used
	// by the Go wrapper to reverse incremental author-stat deltas for each
	// candidate before deleting it (see
	// internal/store/retention/events_retention_untrusted.go).
	SelectUntrustedAuthorEventCandidates(ctx context.Context, arg SelectUntrustedAuthorEventCandidatesParams) ([]string, error)
}

var _ Querier = (*Queries)(nil)
