// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package retentiondb

import (
	"context"
)

type Querier interface {
	// Deletes an explicit, already-decided set of event ids. Used after
	// SelectExpiredEngagementEventCandidates / SelectUntrustedAuthorEventCandidates
	// so the same candidate set that had its incremental stats reversed is the
	// exact set deleted (no re-evaluating the candidate predicate a second time
	// against a possibly-changed table state).
	DeleteEventsByID(ctx context.Context, ids []string) (int64, error)
	GroomSearchDocumentsPrune(ctx context.Context, rowLimit int32) (int64, error)
	GroomSearchDocumentsTrim(ctx context.Context, arg GroomSearchDocumentsTrimParams) (int64, error)
	PruneAuthorRecentEventsByAge(ctx context.Context, arg PruneAuthorRecentEventsByAgeParams) (int64, error)
	PruneAuthorRecentEventsByCap(ctx context.Context, arg PruneAuthorRecentEventsByCapParams) (int64, error)
	// Static retention sweeps for the retention bounded context. Every statement
	// is a bounded DELETE/UPDATE that returns the number of affected rows
	// (:execrows). The hand-written wrappers in internal/store/retention own
	// validation, metrics, and transaction shape; these are pure SQL plumbing.
	PurgeExpiredEngagementEvents(ctx context.Context, arg PurgeExpiredEngagementEventsParams) (int64, error)
	PurgeIdleAccountStates(ctx context.Context, arg PurgeIdleAccountStatesParams) (int64, error)
	PurgeProcessedDeletionEvents(ctx context.Context, arg PurgeProcessedDeletionEventsParams) (int64, error)
	PurgeStaleEventRelays(ctx context.Context, arg PurgeStaleEventRelaysParams) (int64, error)
	PurgeStaleTrustedNoteDiscoveryCandidates(ctx context.Context, arg PurgeStaleTrustedNoteDiscoveryCandidatesParams) (int64, error)
	PurgeStaleTrustedProfileDiscoveryCandidates(ctx context.Context, arg PurgeStaleTrustedProfileDiscoveryCandidatesParams) (int64, error)
	PurgeSupersededReplaceableEvents(ctx context.Context, arg PurgeSupersededReplaceableEventsParams) (int64, error)
	PurgeUntrustedAuthorEventHashtags(ctx context.Context, rowLimit int32) (int64, error)
	PurgeUntrustedAuthorEventURLs(ctx context.Context, rowLimit int32) (int64, error)
	PurgeUntrustedAuthorEvents(ctx context.Context, arg PurgeUntrustedAuthorEventsParams) (int64, error)
	// Read-only counterpart to PurgeExpiredEngagementEvents' candidates CTE,
	// used by the Go wrapper to reverse incremental author-stat deltas for each
	// candidate before deleting it (see internal/store/retention/events_retention.go).
	SelectExpiredEngagementEventCandidates(ctx context.Context, arg SelectExpiredEngagementEventCandidatesParams) ([]string, error)
	// Read-only counterpart to PurgeUntrustedAuthorEvents' candidates CTE, used
	// by the Go wrapper to reverse incremental author-stat deltas for each
	// candidate before deleting it (see
	// internal/store/retention/events_retention_untrusted.go).
	SelectUntrustedAuthorEventCandidates(ctx context.Context, arg SelectUntrustedAuthorEventCandidatesParams) ([]string, error)
}

var _ Querier = (*Queries)(nil)
