// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package retentiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEventsByID = `-- name: DeleteEventsByID :execrows
DELETE FROM events
WHERE id = ANY($1::text[])
`

// Deletes an explicit, already-decided set of event ids. Used after
// SelectExpiredEngagementEventCandidates / SelectUntrustedAuthorEventCandidates
// so the same candidate set that had its incremental stats reversed is the
// exact set deleted (no re-evaluating the candidate predicate a second time
// against a possibly-changed table state).
func (q *Queries) DeleteEventsByID(ctx context.Context, ids []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventsByID, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const groomSearchDocumentsPrune = `-- name: GroomSearchDocumentsPrune :execrows
WITH candidates AS (
    SELECT entity_type, entity_id
    FROM search_documents sd
    WHERE sd.entity_type = 'note'
      AND NOT EXISTS (
        SELECT 1 FROM events e WHERE e.id = sd.entity_id
      )
    LIMIT $1
)
DELETE FROM search_documents sd
USING candidates c
WHERE sd.entity_type = c.entity_type
  AND sd.entity_id = c.entity_id
`

func (q *Queries) GroomSearchDocumentsPrune(ctx context.Context, rowLimit int32) (int64, error) {
	result, err := q.db.Exec(ctx, groomSearchDocumentsPrune, rowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const groomSearchDocumentsTrim = `-- name: GroomSearchDocumentsTrim :execrows
WITH candidates AS (
    SELECT cand.entity_type, cand.entity_id
    FROM search_documents cand
    WHERE cand.entity_type = 'note'
      AND cand.freshness < $2
      AND length(cand.body) > $1
    LIMIT $3
)
UPDATE search_documents sd
SET body = left(sd.body, $1),
    updated_at = now()
FROM candidates c
WHERE sd.entity_type = c.entity_type
  AND sd.entity_id = c.entity_id
`

type GroomSearchDocumentsTrimParams struct {
	MaxBodyChars    int32
	FreshnessBefore pgtype.Timestamptz
	RowLimit        int32
}

func (q *Queries) GroomSearchDocumentsTrim(ctx context.Context, arg GroomSearchDocumentsTrimParams) (int64, error) {
	result, err := q.db.Exec(ctx, groomSearchDocumentsTrim, arg.MaxBodyChars, arg.FreshnessBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneAuthorRecentEventsByAge = `-- name: PruneAuthorRecentEventsByAge :execrows
WITH candidates AS (
    SELECT author_pubkey, event_id
    FROM author_recent_events
    WHERE created_at < $1::bigint
    LIMIT $2
)
DELETE FROM author_recent_events a
USING candidates c
WHERE a.author_pubkey = c.author_pubkey
  AND a.event_id = c.event_id
`

type PruneAuthorRecentEventsByAgeParams struct {
	CreatedBeforeUnix int64
	DeleteBatchLimit  int32
}

func (q *Queries) PruneAuthorRecentEventsByAge(ctx context.Context, arg PruneAuthorRecentEventsByAgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAuthorRecentEventsByAge, arg.CreatedBeforeUnix, arg.DeleteBatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneAuthorRecentEventsByCap = `-- name: PruneAuthorRecentEventsByCap :execrows
WITH touched AS (
    SELECT t.author_pubkey
    FROM (
        SELECT DISTINCT ON (a.author_pubkey) a.author_pubkey, a.projected_at
        FROM author_recent_events a
        WHERE a.projected_at >= $1
        ORDER BY a.author_pubkey, a.projected_at DESC
    ) t
    ORDER BY t.projected_at DESC
    LIMIT $2
),
offenders AS (
    SELECT t.author_pubkey
    FROM touched t
    WHERE (
        SELECT count(*)::bigint
        FROM author_recent_events a
        WHERE a.author_pubkey = t.author_pubkey
    ) > $3::bigint
    LIMIT $4
),
victims AS (
    SELECT r.author_pubkey, r.event_id
    FROM offenders o
    CROSS JOIN LATERAL (
        SELECT a.author_pubkey, a.event_id
        FROM author_recent_events a
        WHERE a.author_pubkey = o.author_pubkey
        ORDER BY a.created_at DESC, a.event_id DESC
        OFFSET $3::bigint
    ) r
    LIMIT $5
)
DELETE FROM author_recent_events a
USING victims v
WHERE a.author_pubkey = v.author_pubkey
  AND a.event_id = v.event_id
`

type PruneAuthorRecentEventsByCapParams struct {
	TouchedSince     pgtype.Timestamptz
	AuthorScanLimit  int32
	PerAuthorCap     int64
	AuthorBatchLimit int32
	DeleteBatchLimit int32
}

// Only authors touched recently can newly exceed the per-author cap; the age
// pass already drains cold rows. Bounding the offender scan to projected_at
// (idx_author_recent_events_projected_at) keeps per-tick cost proportional to
// recent write volume instead of total table size.
func (q *Queries) PruneAuthorRecentEventsByCap(ctx context.Context, arg PruneAuthorRecentEventsByCapParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAuthorRecentEventsByCap,
		arg.TouchedSince,
		arg.AuthorScanLimit,
		arg.PerAuthorCap,
		arg.AuthorBatchLimit,
		arg.DeleteBatchLimit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneFilteredEventTags = `-- name: PruneFilteredEventTags :execrows
WITH candidates AS (
    SELECT et.event_id, et.tag_index, et.value_index
    FROM event_tags et
    INNER JOIN events e ON e.id = et.event_id
    WHERE (et.tag_name = 'p' AND e.kind = 3)
       OR (et.tag_name = 'r' AND e.kind = 10002)
       OR (et.tag_name <> ALL ($1::text[]))
    LIMIT $2
)
DELETE FROM event_tags et
USING candidates c
WHERE et.event_id = c.event_id
  AND et.tag_index = c.tag_index
  AND et.value_index = c.value_index
`

type PruneFilteredEventTagsParams struct {
	AllowedTagNames []string
	RowLimit        int32
}

// Drop event_tags rows that the ingest allowlist would no longer write.
// Matches internal/eventtags.ShouldPersist:
//   - tag_name outside @allowed_tag_names
//   - kind-3 contact-list p-tags
//   - kind-10002 relay-list r-tags
//
// events.raw_json remains the source of truth; this only shrinks the
// derived join index. Batched via LIMIT so the worker catchup loop can
// drain hundreds of millions of rows without a single long transaction.
func (q *Queries) PruneFilteredEventTags(ctx context.Context, arg PruneFilteredEventTagsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneFilteredEventTags, arg.AllowedTagNames, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneOrphanedAppliedStatDeltas = `-- name: PruneOrphanedAppliedStatDeltas :execrows
WITH candidates AS (
    SELECT d.event_id, d.projection
    FROM applied_stat_deltas d
    WHERE d.applied_at < $1
      AND NOT EXISTS (
        SELECT 1 FROM events e WHERE e.id = d.event_id
      )
    LIMIT $2
)
DELETE FROM applied_stat_deltas d
USING candidates c
WHERE d.event_id = c.event_id
  AND d.projection = c.projection
`

type PruneOrphanedAppliedStatDeltasParams struct {
	AppliedBefore pgtype.Timestamptz
	RowLimit      int32
}

// Deletes applied_stat_deltas ledger rows whose source event no longer
// exists in events. This is the only condition under which a ledger row is
// guaranteed to serve no further purpose: as long as the event exists,
// projection_incremental_stats.go's unclaimStatDeltaTx path may still need
// the row to gate a future decrement (see reverseAndDeleteTx in retention.go,
// which atomically reverses deltas and deletes the event together, itself
// deleting the ledger rows it unclaims). Once the event row is gone — via
// that reversal-aware path, or via a purge that never touched incremental
// stats (PurgeSupersededReplaceableEvents, PurgeProcessedDeletionEvents) —
// any ledger row still referencing that event_id is a pure orphan.
//
// applied_before is a conservative grace buffer on top of the orphan check
// (not itself a correctness requirement) that keeps freshly-inserted rows
// out of the scan and bounds it via idx_applied_stat_deltas_applied_at.
func (q *Queries) PruneOrphanedAppliedStatDeltas(ctx context.Context, arg PruneOrphanedAppliedStatDeltasParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneOrphanedAppliedStatDeltas, arg.AppliedBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeExpiredEngagementEvents = `-- name: PurgeExpiredEngagementEvents :execrows

WITH candidates AS (
    SELECT e.id
    FROM events e
    WHERE e.kind IN (6, 7, 9735)
      AND e.created_at < $1::bigint
      AND NOT EXISTS (
        SELECT 1
        FROM jobs j
        WHERE j.idempotency_key = 'derive_event_bundle:' || e.id
          AND (
            j.status IN ('pending', 'running')
            OR (j.status = 'dead' AND j.updated_at > $2)
          )
      )
    ORDER BY e.created_at ASC, e.id ASC
    LIMIT $3
)
DELETE FROM events e
USING candidates c
WHERE e.id = c.id
`

type PurgeExpiredEngagementEventsParams struct {
	CreatedBeforeUnix int64
	DeadGraceBefore   pgtype.Timestamptz
	RowLimit          int32
}

// Static retention sweeps for the retention bounded context. Every statement
// is a bounded DELETE/UPDATE that returns the number of affected rows
// (:execrows). The hand-written wrappers in internal/store/retention own
// validation, metrics, and transaction shape; these are pure SQL plumbing.
func (q *Queries) PurgeExpiredEngagementEvents(ctx context.Context, arg PurgeExpiredEngagementEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredEngagementEvents, arg.CreatedBeforeUnix, arg.DeadGraceBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeIdleAccountStates = `-- name: PurgeIdleAccountStates :execrows
WITH candidates AS (
    SELECT a.pubkey
    FROM account_states a
    WHERE a.state IN ('unknown', 'observed')
      AND a.manual_override IS NULL
      AND a.last_observed_at < CASE
        WHEN EXISTS (
            SELECT 1 FROM trust_graph_snapshot s WHERE s.pubkey = a.pubkey
        ) THEN $1::timestamptz
        ELSE $2::timestamptz
      END
    LIMIT $3
)
DELETE FROM account_states a
USING candidates c
WHERE a.pubkey = c.pubkey
`

type PurgeIdleAccountStatesParams struct {
	TrustedBefore   pgtype.Timestamptz
	UntrustedBefore pgtype.Timestamptz
	RowLimit        int32
}

func (q *Queries) PurgeIdleAccountStates(ctx context.Context, arg PurgeIdleAccountStatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeIdleAccountStates, arg.TrustedBefore, arg.UntrustedBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeProcessedDeletionEvents = `-- name: PurgeProcessedDeletionEvents :execrows
WITH candidates AS (
    SELECT e.id
    FROM events e
    WHERE e.kind = 5
      AND e.created_at < $1::bigint
      AND NOT EXISTS (
        SELECT 1
        FROM jobs j
        WHERE j.idempotency_key = 'derive_event_bundle:' || e.id
          AND (
            j.status IN ('pending', 'running')
            OR (j.status = 'dead' AND j.updated_at > $2)
          )
      )
    ORDER BY e.created_at ASC, e.id ASC
    LIMIT $3
)
DELETE FROM events e
USING candidates c
WHERE e.id = c.id
`

type PurgeProcessedDeletionEventsParams struct {
	CreatedBeforeUnix int64
	DeadGraceBefore   pgtype.Timestamptz
	RowLimit          int32
}

func (q *Queries) PurgeProcessedDeletionEvents(ctx context.Context, arg PurgeProcessedDeletionEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeProcessedDeletionEvents, arg.CreatedBeforeUnix, arg.DeadGraceBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeStaleEventRelays = `-- name: PurgeStaleEventRelays :execrows
WITH candidates AS (
    SELECT er.event_id, er.relay_url
    FROM event_relays er
    WHERE er.seen_at < $1
      AND NOT er.is_first_seen
    ORDER BY er.seen_at ASC, er.event_id ASC, er.relay_url ASC
    LIMIT $2
)
DELETE FROM event_relays er
USING candidates c
WHERE er.event_id = c.event_id
  AND er.relay_url = c.relay_url
`

type PurgeStaleEventRelaysParams struct {
	SeenBefore pgtype.Timestamptz
	RowLimit   int32
}

// Deletes duplicate provenance older than seen_before. The earliest-seen
// row per event (is_first_seen, maintained by triggers in migration 000070)
// is never deleted. Served by idx_event_relays_purge_nonfirst_seen_at so
// cost tracks deletable backlog, not total table size.
func (q *Queries) PurgeStaleEventRelays(ctx context.Context, arg PurgeStaleEventRelaysParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeStaleEventRelays, arg.SeenBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeStaleTrustedNoteDiscoveryCandidates = `-- name: PurgeStaleTrustedNoteDiscoveryCandidates :execrows
WITH candidates AS (
    SELECT cand.event_id
    FROM trusted_note_discovery_candidates cand
    WHERE (cand.min_hops IS NOT NULL AND cand.projected_at < $1)
       OR (cand.min_hops IS NULL AND cand.projected_at < $2)
    LIMIT $3
)
DELETE FROM trusted_note_discovery_candidates t
USING candidates c
WHERE t.event_id = c.event_id
`

type PurgeStaleTrustedNoteDiscoveryCandidatesParams struct {
	TrustedBefore   pgtype.Timestamptz
	UntrustedBefore pgtype.Timestamptz
	RowLimit        int32
}

func (q *Queries) PurgeStaleTrustedNoteDiscoveryCandidates(ctx context.Context, arg PurgeStaleTrustedNoteDiscoveryCandidatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeStaleTrustedNoteDiscoveryCandidates, arg.TrustedBefore, arg.UntrustedBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeStaleTrustedProfileDiscoveryCandidates = `-- name: PurgeStaleTrustedProfileDiscoveryCandidates :execrows
WITH candidates AS (
    SELECT cand.pubkey
    FROM trusted_profile_discovery_candidates cand
    WHERE (cand.min_hops IS NOT NULL AND cand.projected_at < $1)
       OR (cand.min_hops IS NULL AND cand.projected_at < $2)
    LIMIT $3
)
DELETE FROM trusted_profile_discovery_candidates t
USING candidates c
WHERE t.pubkey = c.pubkey
`

type PurgeStaleTrustedProfileDiscoveryCandidatesParams struct {
	TrustedBefore   pgtype.Timestamptz
	UntrustedBefore pgtype.Timestamptz
	RowLimit        int32
}

func (q *Queries) PurgeStaleTrustedProfileDiscoveryCandidates(ctx context.Context, arg PurgeStaleTrustedProfileDiscoveryCandidatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeStaleTrustedProfileDiscoveryCandidates, arg.TrustedBefore, arg.UntrustedBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeSupersededReplaceableEvents = `-- name: PurgeSupersededReplaceableEvents :execrows
WITH candidates AS (
    SELECT e.id
    FROM events e
    JOIN LATERAL (
        SELECT COALESCE((
            SELECT et.value
            FROM event_tags et
            WHERE et.event_id = e.id
              AND et.tag_name = 'd'
              AND et.tag_index >= 0
              AND et.value_index = 0
            ORDER BY et.tag_index ASC
            LIMIT 1
        ), '') AS d_tag
    ) dd ON true
    JOIN replaceable_state rs
      ON rs.pubkey = e.pubkey
     AND rs.kind = e.kind
     AND rs.d_tag = dd.d_tag
    WHERE e.kind = ANY($1::int[])
      AND e.first_seen_at < $2
      AND (
        rs.created_at > e.created_at
        OR (rs.created_at = e.created_at AND rs.event_id > e.id)
      )
      AND NOT EXISTS (
        SELECT 1
        FROM jobs j
        WHERE j.idempotency_key = 'derive_event_bundle:' || e.id
          AND (
            j.status IN ('pending', 'running')
            OR (j.status = 'dead' AND j.updated_at > $3)
          )
      )
    ORDER BY e.created_at ASC, e.id ASC
    LIMIT $4
)
DELETE FROM events e
USING candidates c
WHERE e.id = c.id
`

type PurgeSupersededReplaceableEventsParams struct {
	Kinds            []int32
	SupersededBefore pgtype.Timestamptz
	DeadGraceBefore  pgtype.Timestamptz
	RowLimit         int32
}

func (q *Queries) PurgeSupersededReplaceableEvents(ctx context.Context, arg PurgeSupersededReplaceableEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeSupersededReplaceableEvents,
		arg.Kinds,
		arg.SupersededBefore,
		arg.DeadGraceBefore,
		arg.RowLimit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeUntrustedAuthorEventHashtags = `-- name: PurgeUntrustedAuthorEventHashtags :execrows
WITH candidates AS (
    SELECT h.event_id, h.hashtag
    FROM event_hashtags h
    WHERE EXISTS (SELECT 1 FROM trust_graph_snapshot)
      AND NOT EXISTS (
        SELECT 1 FROM trust_graph_snapshot s
        WHERE s.pubkey = h.author_pubkey
      )
    ORDER BY h.created_at ASC, h.event_id ASC, h.hashtag ASC
    LIMIT $1
)
DELETE FROM event_hashtags h
USING candidates c
WHERE h.event_id = c.event_id
  AND h.hashtag = c.hashtag
`

func (q *Queries) PurgeUntrustedAuthorEventHashtags(ctx context.Context, rowLimit int32) (int64, error) {
	result, err := q.db.Exec(ctx, purgeUntrustedAuthorEventHashtags, rowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeUntrustedAuthorEventURLs = `-- name: PurgeUntrustedAuthorEventURLs :execrows
WITH candidates AS (
    SELECT u.event_id, u.url
    FROM event_urls u
    WHERE EXISTS (SELECT 1 FROM trust_graph_snapshot)
      AND NOT EXISTS (
        SELECT 1 FROM trust_graph_snapshot s
        WHERE s.pubkey = u.author_pubkey
      )
    ORDER BY u.created_at ASC, u.event_id ASC, u.url ASC
    LIMIT $1
)
DELETE FROM event_urls u
USING candidates c
WHERE u.event_id = c.event_id
  AND u.url = c.url
`

func (q *Queries) PurgeUntrustedAuthorEventURLs(ctx context.Context, rowLimit int32) (int64, error) {
	result, err := q.db.Exec(ctx, purgeUntrustedAuthorEventURLs, rowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeUntrustedAuthorEvents = `-- name: PurgeUntrustedAuthorEvents :execrows
WITH candidates AS (
    SELECT e.id
    FROM events e
    WHERE e.kind IN (1, 4, 5, 9802, 10000, 10003, 30023)
      AND e.created_at < $1::bigint
      AND e.first_seen_at < $2
      AND EXISTS (SELECT 1 FROM trust_graph_snapshot)
      AND NOT EXISTS (
        SELECT 1 FROM trust_graph_snapshot s
        WHERE s.pubkey = e.pubkey
      )
      -- Kind-1 replies accepted via target-exists ingest are kept so conversation
      -- totals are not rolled back by untrusted-author retention. Root notes from
      -- untrusted authors remain purgeable.
      AND NOT (
        e.kind = 1
        AND EXISTS (
          SELECT 1 FROM thread_edges te WHERE te.child_event_id = e.id
        )
      )
      AND NOT EXISTS (
        SELECT 1
        FROM jobs j
        WHERE j.idempotency_key = 'derive_event_bundle:' || e.id
          AND (
            j.status IN ('pending', 'running')
            OR (j.status = 'dead' AND j.updated_at > $3)
          )
      )
    ORDER BY e.created_at ASC, e.id ASC
    LIMIT $4
)
DELETE FROM events e
USING candidates c
WHERE e.id = c.id
`

type PurgeUntrustedAuthorEventsParams struct {
	CreatedBeforeUnix int64
	FirstSeenBefore   pgtype.Timestamptz
	DeadGraceBefore   pgtype.Timestamptz
	RowLimit          int32
}

func (q *Queries) PurgeUntrustedAuthorEvents(ctx context.Context, arg PurgeUntrustedAuthorEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeUntrustedAuthorEvents,
		arg.CreatedBeforeUnix,
		arg.FirstSeenBefore,
		arg.DeadGraceBefore,
		arg.RowLimit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectExpiredEngagementEventCandidates = `-- name: SelectExpiredEngagementEventCandidates :many
SELECT e.id
FROM events e
WHERE e.kind IN (6, 7, 9735)
  AND e.created_at < $1::bigint
  AND NOT EXISTS (
    SELECT 1
    FROM jobs j
    WHERE j.idempotency_key = 'derive_event_bundle:' || e.id
      AND (
        j.status IN ('pending', 'running')
        OR (j.status = 'dead' AND j.updated_at > $2)
      )
  )
ORDER BY e.created_at ASC, e.id ASC
LIMIT $3
`

type SelectExpiredEngagementEventCandidatesParams struct {
	CreatedBeforeUnix int64
	DeadGraceBefore   pgtype.Timestamptz
	RowLimit          int32
}

// Read-only counterpart to PurgeExpiredEngagementEvents' candidates CTE,
// used by the Go wrapper to reverse incremental author-stat deltas for each
// candidate before deleting it (see internal/store/retention/events_retention.go).
func (q *Queries) SelectExpiredEngagementEventCandidates(ctx context.Context, arg SelectExpiredEngagementEventCandidatesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, selectExpiredEngagementEventCandidates, arg.CreatedBeforeUnix, arg.DeadGraceBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUntrustedAuthorEventCandidates = `-- name: SelectUntrustedAuthorEventCandidates :many
SELECT e.id
FROM events e
WHERE e.kind IN (1, 4, 5, 9802, 10000, 10003, 30023)
  AND e.created_at < $1::bigint
  AND e.first_seen_at < $2
  AND EXISTS (SELECT 1 FROM trust_graph_snapshot)
  AND NOT EXISTS (
    SELECT 1 FROM trust_graph_snapshot s
    WHERE s.pubkey = e.pubkey
  )
  AND NOT (
    e.kind = 1
    AND EXISTS (
      SELECT 1 FROM thread_edges te WHERE te.child_event_id = e.id
    )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM jobs j
    WHERE j.idempotency_key = 'derive_event_bundle:' || e.id
      AND (
        j.status IN ('pending', 'running')
        OR (j.status = 'dead' AND j.updated_at > $3)
      )
  )
ORDER BY e.created_at ASC, e.id ASC
LIMIT $4
`

type SelectUntrustedAuthorEventCandidatesParams struct {
	CreatedBeforeUnix int64
	FirstSeenBefore   pgtype.Timestamptz
	DeadGraceBefore   pgtype.Timestamptz
	RowLimit          int32
}

// Read-only counterpart to PurgeUntrustedAuthorEvents' candidates CTE, used
// by the Go wrapper to reverse incremental author-stat deltas for each
// candidate before deleting it (see
// internal/store/retention/events_retention_untrusted.go).
func (q *Queries) SelectUntrustedAuthorEventCandidates(ctx context.Context, arg SelectUntrustedAuthorEventCandidatesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, selectUntrustedAuthorEventCandidates,
		arg.CreatedBeforeUnix,
		arg.FirstSeenBefore,
		arg.DeadGraceBefore,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
