// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package retentiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const groomSearchDocumentsPrune = `-- name: GroomSearchDocumentsPrune :execrows
WITH candidates AS (
    SELECT entity_type, entity_id
    FROM search_documents sd
    WHERE sd.entity_type = 'note'
      AND NOT EXISTS (
        SELECT 1 FROM events e WHERE e.id = sd.entity_id
      )
    LIMIT $1
)
DELETE FROM search_documents sd
USING candidates c
WHERE sd.entity_type = c.entity_type
  AND sd.entity_id = c.entity_id
`

func (q *Queries) GroomSearchDocumentsPrune(ctx context.Context, rowLimit int32) (int64, error) {
	result, err := q.db.Exec(ctx, groomSearchDocumentsPrune, rowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const groomSearchDocumentsTrim = `-- name: GroomSearchDocumentsTrim :execrows
WITH candidates AS (
    SELECT cand.entity_type, cand.entity_id
    FROM search_documents cand
    WHERE cand.entity_type = 'note'
      AND cand.freshness < $2
      AND length(cand.body) > $1
    LIMIT $3
)
UPDATE search_documents sd
SET body = left(sd.body, $1),
    updated_at = now()
FROM candidates c
WHERE sd.entity_type = c.entity_type
  AND sd.entity_id = c.entity_id
`

type GroomSearchDocumentsTrimParams struct {
	MaxBodyChars    int32
	FreshnessBefore pgtype.Timestamptz
	RowLimit        int32
}

func (q *Queries) GroomSearchDocumentsTrim(ctx context.Context, arg GroomSearchDocumentsTrimParams) (int64, error) {
	result, err := q.db.Exec(ctx, groomSearchDocumentsTrim, arg.MaxBodyChars, arg.FreshnessBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneAuthorRecentEventsByAge = `-- name: PruneAuthorRecentEventsByAge :execrows
WITH candidates AS (
    SELECT author_pubkey, event_id
    FROM author_recent_events
    WHERE created_at < $1::bigint
    LIMIT $2
)
DELETE FROM author_recent_events a
USING candidates c
WHERE a.author_pubkey = c.author_pubkey
  AND a.event_id = c.event_id
`

type PruneAuthorRecentEventsByAgeParams struct {
	CreatedBeforeUnix int64
	DeleteBatchLimit  int32
}

func (q *Queries) PruneAuthorRecentEventsByAge(ctx context.Context, arg PruneAuthorRecentEventsByAgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAuthorRecentEventsByAge, arg.CreatedBeforeUnix, arg.DeleteBatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneAuthorRecentEventsByCap = `-- name: PruneAuthorRecentEventsByCap :execrows
WITH offenders AS (
    SELECT author_pubkey
    FROM author_recent_events
    GROUP BY author_pubkey
    HAVING count(*) > $1::bigint
    LIMIT $2
),
victims AS (
    SELECT r.author_pubkey, r.event_id
    FROM offenders o
    CROSS JOIN LATERAL (
        SELECT a.author_pubkey, a.event_id
        FROM author_recent_events a
        WHERE a.author_pubkey = o.author_pubkey
        ORDER BY a.created_at DESC, a.event_id DESC
        OFFSET $1::bigint
    ) r
    LIMIT $3
)
DELETE FROM author_recent_events a
USING victims v
WHERE a.author_pubkey = v.author_pubkey
  AND a.event_id = v.event_id
`

type PruneAuthorRecentEventsByCapParams struct {
	PerAuthorCap     int64
	AuthorBatchLimit int32
	DeleteBatchLimit int32
}

func (q *Queries) PruneAuthorRecentEventsByCap(ctx context.Context, arg PruneAuthorRecentEventsByCapParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAuthorRecentEventsByCap, arg.PerAuthorCap, arg.AuthorBatchLimit, arg.DeleteBatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeExpiredEngagementEvents = `-- name: PurgeExpiredEngagementEvents :execrows

WITH candidates AS (
    SELECT e.id
    FROM events e
    WHERE e.kind IN (6, 7, 9735)
      AND e.created_at < $1::bigint
      AND NOT EXISTS (
        SELECT 1
        FROM jobs j
        WHERE j.idempotency_key = 'derive_event_bundle:' || e.id
          AND (
            j.status IN ('pending', 'running')
            OR (j.status = 'dead' AND j.updated_at > $2)
          )
      )
    ORDER BY e.created_at ASC, e.id ASC
    LIMIT $3
)
DELETE FROM events e
USING candidates c
WHERE e.id = c.id
`

type PurgeExpiredEngagementEventsParams struct {
	CreatedBeforeUnix int64
	DeadGraceBefore   pgtype.Timestamptz
	RowLimit          int32
}

// Static retention sweeps for the retention bounded context. Every statement
// is a bounded DELETE/UPDATE that returns the number of affected rows
// (:execrows). The hand-written wrappers in internal/store/retention own
// validation, metrics, and transaction shape; these are pure SQL plumbing.
func (q *Queries) PurgeExpiredEngagementEvents(ctx context.Context, arg PurgeExpiredEngagementEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredEngagementEvents, arg.CreatedBeforeUnix, arg.DeadGraceBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeIdleAccountStates = `-- name: PurgeIdleAccountStates :execrows
WITH candidates AS (
    SELECT a.pubkey
    FROM account_states a
    WHERE a.state IN ('unknown', 'observed')
      AND a.manual_override IS NULL
      AND a.last_observed_at < CASE
        WHEN EXISTS (
            SELECT 1 FROM trust_graph_snapshot s WHERE s.pubkey = a.pubkey
        ) THEN $1::timestamptz
        ELSE $2::timestamptz
      END
    LIMIT $3
)
DELETE FROM account_states a
USING candidates c
WHERE a.pubkey = c.pubkey
`

type PurgeIdleAccountStatesParams struct {
	TrustedBefore   pgtype.Timestamptz
	UntrustedBefore pgtype.Timestamptz
	RowLimit        int32
}

func (q *Queries) PurgeIdleAccountStates(ctx context.Context, arg PurgeIdleAccountStatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeIdleAccountStates, arg.TrustedBefore, arg.UntrustedBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeProcessedDeletionEvents = `-- name: PurgeProcessedDeletionEvents :execrows
WITH candidates AS (
    SELECT e.id
    FROM events e
    WHERE e.kind = 5
      AND e.created_at < $1::bigint
      AND NOT EXISTS (
        SELECT 1
        FROM jobs j
        WHERE j.idempotency_key = 'derive_event_bundle:' || e.id
          AND (
            j.status IN ('pending', 'running')
            OR (j.status = 'dead' AND j.updated_at > $2)
          )
      )
    ORDER BY e.created_at ASC, e.id ASC
    LIMIT $3
)
DELETE FROM events e
USING candidates c
WHERE e.id = c.id
`

type PurgeProcessedDeletionEventsParams struct {
	CreatedBeforeUnix int64
	DeadGraceBefore   pgtype.Timestamptz
	RowLimit          int32
}

func (q *Queries) PurgeProcessedDeletionEvents(ctx context.Context, arg PurgeProcessedDeletionEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeProcessedDeletionEvents, arg.CreatedBeforeUnix, arg.DeadGraceBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeStaleEventRelays = `-- name: PurgeStaleEventRelays :execrows
WITH candidates AS (
    SELECT er.event_id, er.relay_url
    FROM event_relays er
    WHERE er.seen_at < $1
      AND EXISTS (
        SELECT 1
        FROM event_relays first
        WHERE first.event_id = er.event_id
          AND (
            first.seen_at < er.seen_at
            OR (first.seen_at = er.seen_at AND first.relay_url < er.relay_url)
          )
      )
    LIMIT $2
)
DELETE FROM event_relays er
USING candidates c
WHERE er.event_id = c.event_id
  AND er.relay_url = c.relay_url
`

type PurgeStaleEventRelaysParams struct {
	SeenBefore pgtype.Timestamptz
	RowLimit   int32
}

func (q *Queries) PurgeStaleEventRelays(ctx context.Context, arg PurgeStaleEventRelaysParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeStaleEventRelays, arg.SeenBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeStaleTrustedNoteDiscoveryCandidates = `-- name: PurgeStaleTrustedNoteDiscoveryCandidates :execrows
WITH candidates AS (
    SELECT cand.event_id
    FROM trusted_note_discovery_candidates cand
    WHERE (cand.min_hops IS NOT NULL AND cand.projected_at < $1)
       OR (cand.min_hops IS NULL AND cand.projected_at < $2)
    LIMIT $3
)
DELETE FROM trusted_note_discovery_candidates t
USING candidates c
WHERE t.event_id = c.event_id
`

type PurgeStaleTrustedNoteDiscoveryCandidatesParams struct {
	TrustedBefore   pgtype.Timestamptz
	UntrustedBefore pgtype.Timestamptz
	RowLimit        int32
}

func (q *Queries) PurgeStaleTrustedNoteDiscoveryCandidates(ctx context.Context, arg PurgeStaleTrustedNoteDiscoveryCandidatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeStaleTrustedNoteDiscoveryCandidates, arg.TrustedBefore, arg.UntrustedBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeStaleTrustedProfileDiscoveryCandidates = `-- name: PurgeStaleTrustedProfileDiscoveryCandidates :execrows
WITH candidates AS (
    SELECT cand.pubkey
    FROM trusted_profile_discovery_candidates cand
    WHERE (cand.min_hops IS NOT NULL AND cand.projected_at < $1)
       OR (cand.min_hops IS NULL AND cand.projected_at < $2)
    LIMIT $3
)
DELETE FROM trusted_profile_discovery_candidates t
USING candidates c
WHERE t.pubkey = c.pubkey
`

type PurgeStaleTrustedProfileDiscoveryCandidatesParams struct {
	TrustedBefore   pgtype.Timestamptz
	UntrustedBefore pgtype.Timestamptz
	RowLimit        int32
}

func (q *Queries) PurgeStaleTrustedProfileDiscoveryCandidates(ctx context.Context, arg PurgeStaleTrustedProfileDiscoveryCandidatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeStaleTrustedProfileDiscoveryCandidates, arg.TrustedBefore, arg.UntrustedBefore, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeSupersededReplaceableEvents = `-- name: PurgeSupersededReplaceableEvents :execrows
WITH candidates AS (
    SELECT e.id
    FROM events e
    JOIN LATERAL (
        SELECT COALESCE((
            SELECT et.value
            FROM event_tags et
            WHERE et.event_id = e.id
              AND et.tag_name = 'd'
              AND et.tag_index >= 0
              AND et.value_index = 0
            ORDER BY et.tag_index ASC
            LIMIT 1
        ), '') AS d_tag
    ) dd ON true
    JOIN replaceable_state rs
      ON rs.pubkey = e.pubkey
     AND rs.kind = e.kind
     AND rs.d_tag = dd.d_tag
    WHERE e.kind = ANY($1::int[])
      AND e.first_seen_at < $2
      AND (
        rs.created_at > e.created_at
        OR (rs.created_at = e.created_at AND rs.event_id > e.id)
      )
      AND NOT EXISTS (
        SELECT 1
        FROM jobs j
        WHERE j.idempotency_key = 'derive_event_bundle:' || e.id
          AND (
            j.status IN ('pending', 'running')
            OR (j.status = 'dead' AND j.updated_at > $3)
          )
      )
    ORDER BY e.created_at ASC, e.id ASC
    LIMIT $4
)
DELETE FROM events e
USING candidates c
WHERE e.id = c.id
`

type PurgeSupersededReplaceableEventsParams struct {
	Kinds            []int32
	SupersededBefore pgtype.Timestamptz
	DeadGraceBefore  pgtype.Timestamptz
	RowLimit         int32
}

func (q *Queries) PurgeSupersededReplaceableEvents(ctx context.Context, arg PurgeSupersededReplaceableEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeSupersededReplaceableEvents,
		arg.Kinds,
		arg.SupersededBefore,
		arg.DeadGraceBefore,
		arg.RowLimit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeUntrustedAuthorEvents = `-- name: PurgeUntrustedAuthorEvents :execrows
WITH candidates AS (
    SELECT e.id
    FROM events e
    WHERE e.kind IN (1, 4, 9802, 10000, 10003, 30023)
      AND e.created_at < $1::bigint
      AND e.first_seen_at < $2
      AND EXISTS (SELECT 1 FROM trust_graph_snapshot)
      AND NOT EXISTS (
        SELECT 1 FROM trust_graph_snapshot s
        WHERE s.pubkey = e.pubkey
      )
      AND NOT EXISTS (
        SELECT 1
        FROM jobs j
        WHERE j.idempotency_key = 'derive_event_bundle:' || e.id
          AND (
            j.status IN ('pending', 'running')
            OR (j.status = 'dead' AND j.updated_at > $3)
          )
      )
    ORDER BY e.created_at ASC, e.id ASC
    LIMIT $4
)
DELETE FROM events e
USING candidates c
WHERE e.id = c.id
`

type PurgeUntrustedAuthorEventsParams struct {
	CreatedBeforeUnix int64
	FirstSeenBefore   pgtype.Timestamptz
	DeadGraceBefore   pgtype.Timestamptz
	RowLimit          int32
}

func (q *Queries) PurgeUntrustedAuthorEvents(ctx context.Context, arg PurgeUntrustedAuthorEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeUntrustedAuthorEvents,
		arg.CreatedBeforeUnix,
		arg.FirstSeenBefore,
		arg.DeadGraceBefore,
		arg.RowLimit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
