package config

import (
	"cmp"
	"slices"
	"strings"
)

// EnvVarDoc describes one environment variable consumed by runtime config.
type EnvVarDoc struct {
	Name         string
	Runtimes     []string
	Required     bool
	DefaultValue string
	Description  string
}

// GenerateConfigurationMarkdown renders docs/configuration.md.
func GenerateConfigurationMarkdown() string {
	docs := append([]EnvVarDoc(nil), ConfigEnvDocs()...)
	for i := range docs {
		runtimes := append([]string(nil), docs[i].Runtimes...)
		slices.Sort(runtimes)
		docs[i].Runtimes = runtimes
	}
	slices.SortFunc(docs, func(a, b EnvVarDoc) int {
		return cmp.Compare(a.Name, b.Name)
	})

	var b strings.Builder
	b.WriteString("# Configuration\n\n")
	b.WriteString("Use this page as the environment-variable reference for NostrMash runtimes.\n")
	b.WriteString("It is generated by `go run ./cmd/configdoc` from `internal/config` metadata.\n")
	b.WriteString("Read [docs/operations.md](operations.md) for operator workflow and tuning context; use this page as the lookup layer for exact variable names, defaults, and runtime ownership.\n")
	b.WriteString("Operational values consumed outside `internal/config` such as `LOG_LEVEL`, deployment metadata like `APP_VERSION`, and test-only knobs like `TEST_DATABASE_URL` are intentionally out of scope.\n")
	b.WriteString("Do not hand-edit this file.\n\n")
	b.WriteString("| Env var | Runtime(s) | Required | Default | Description |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, doc := range docs {
		required := "optional"
		if doc.Required {
			required = "required"
		}
		defaultValue := doc.DefaultValue
		if strings.TrimSpace(defaultValue) == "" {
			defaultValue = "-"
		}
		b.WriteString("| `")
		b.WriteString(doc.Name)
		b.WriteString("` | ")
		b.WriteString("`")
		b.WriteString(strings.Join(doc.Runtimes, ", "))
		b.WriteString("` | ")
		b.WriteString(required)
		b.WriteString(" | `")
		b.WriteString(defaultValue)
		b.WriteString("` | ")
		b.WriteString(doc.Description)
		b.WriteString(" |\n")
	}
	return b.String()
}
