package config

func configEnvDocsWorker() []EnvVarDoc {
	return []EnvVarDoc{
		{
			Name:         "WORKER_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "4",
			Description:  "Worker goroutine concurrency for the default job pool (legacy / backlog work).",
		},
		{
			Name:         "WORKER_LIVE_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "WORKER_CONCURRENCY",
			Description:  "Worker goroutine concurrency for the live job pool (events from real-time relay subscriptions). Set to 0 to disable.",
		},
		{
			Name:         "WORKER_BACKFILL_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "WORKER_CONCURRENCY",
			Description:  "Worker goroutine concurrency for the backfill job pool (events from historical fetch / trust fetch / metadata discovery). Set to 0 to disable.",
		},
		{
			Name:         "WORKER_CLAIM_BATCH_SIZE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "10",
			Description:  "Maximum number of jobs claimed per claim-loop iteration for each worker pool.",
		},
		{
			Name:         "WORKER_AUTHOR_ANALYTICS_SWEEPER_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable the background sweeper that drains pending_author_analytics_recomputes (per-author analytics rebuilds deferred from derive_event_bundle).",
		},
		{
			Name:         "WORKER_AUTHOR_ANALYTICS_SWEEPER_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "5s",
			Description:  "Polling interval between author-analytics sweeper batches when the dirty queue is empty. Sweepers loop without sleeping while batches are full.",
		},
		{
			Name:         "WORKER_AUTHOR_ANALYTICS_SWEEPER_BATCH_SIZE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "25",
			Description:  "Maximum dirty pubkeys claimed and rebuilt per author-analytics sweeper batch.",
		},
		{
			Name:         "WORKER_AUTHOR_ANALYTICS_SWEEPER_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "4",
			Description:  "Number of concurrent author-analytics sweeper goroutines. Each independently claims dirty pubkeys via FOR UPDATE SKIP LOCKED.",
		},
		{
			Name:         "WORKER_MEILISEARCH_SWEEPER_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable the background sweeper that drains pending_meilisearch_syncs (per-event Meilisearch index syncs deferred from derive_event_bundle). Has no effect when MEILI_ENABLED=false.",
		},
		{
			Name:         "WORKER_MEILISEARCH_SWEEPER_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "2s",
			Description:  "Polling interval between Meilisearch sweeper batches when the dirty queue is empty. Sweepers loop without sleeping while batches are full.",
		},
		{
			Name:         "WORKER_MEILISEARCH_SWEEPER_BATCH_SIZE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "50",
			Description:  "Maximum dirty events claimed and synced to Meilisearch per sweeper batch.",
		},
		{
			Name:         "WORKER_MEILISEARCH_SWEEPER_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "4",
			Description:  "Number of concurrent Meilisearch sweeper goroutines. Each independently claims dirty events via FOR UPDATE SKIP LOCKED.",
		},
		{
			Name:         "WORKER_JOB_RUNNING_TIMEOUT",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "15m0s",
			Description:  "Lease timeout for running jobs before stale recovery treats them as orphaned.",
		},
		{
			Name:         "WORKER_JOB_STALE_RECOVERY_BATCH_LIMIT",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "100",
			Description:  "Maximum stale running jobs processed per recovery interval.",
		},
		{
			Name:         "WORKER_JOB_STALE_RECOVERY_INTERVAL",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "30s",
			Description:  "Interval between stale running-job recovery scans.",
		},
		{
			Name:         "WORKER_JOB_RETENTION_DEAD_MAX_AGE",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "336h0m0s",
			Description:  "Max age for dead jobs (purged by finished_at) before retention purges terminal history.",
		},
		{
			Name:         "WORKER_JOB_RETENTION_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum terminal jobs deleted per retention purge run.",
		},
		{
			Name:         "WORKER_JOB_RETENTION_ENABLED",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable periodic retention purge of terminal job history. Applied independently in each worker process.",
		},
		{
			Name:         "WORKER_JOB_RETENTION_RUN_INTERVAL",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "15m0s",
			Description:  "Interval between terminal job retention purge runs.",
		},
		{
			Name:         "WORKER_JOB_RETENTION_SUCCEEDED_MAX_AGE",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "24h0m0s",
			Description:  "Max age for succeeded jobs (purged by finished_at) before retention purges terminal history.",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_PAYLOAD_TRIM_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "500",
			Description:  "Maximum invalid_events rows with raw_payload trimmed to NULL per retention run when payload trimming is enabled.",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_PAYLOAD_TRIM_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable optional second-stage invalid_events payload trimming (raw_payload set to NULL before full-row retention purge).",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_PAYLOAD_TRIM_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "168h0m0s",
			Description:  "Max age for invalid_events rows before payload-only trimming (must be smaller than WORKER_INVALID_EVENTS_RETENTION_MAX_AGE).",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_RETENTION_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "500",
			Description:  "Maximum invalid_events rows deleted per retention purge run.",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_RETENTION_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable periodic invalid_events retention purge.",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_RETENTION_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "720h0m0s",
			Description:  "Max age for invalid_events rows before retention purge.",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_RETENTION_RUN_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "1h0m0s",
			Description:  "Interval between invalid_events retention purge runs.",
		},
	}
}
