package config

func configEnvDocsIngestor() []EnvVarDoc {
	return []EnvVarDoc{
		{
			Name:         "INGESTOR_BACKFILL_CONNECT_TIMEOUT",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "10s",
			Description:  "Connection timeout used by backfill relay sessions.",
		},
		{
			Name:         "INGESTOR_BACKFILL_EMPTY_PAGE_MAX",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "2",
			Description:  "Maximum consecutive empty pages before backfill stops.",
		},
		{
			Name:         "INGESTOR_BACKFILL_ENABLED",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Enables bootstrap/backfill mode.",
		},
		{
			Name:         "INGESTOR_BACKFILL_IDLE_TIMEOUT",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "3s",
			Description:  "Idle timeout while waiting for backfill events.",
		},
		{
			Name:         "INGESTOR_BACKFILL_MODE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "backfill",
			Description:  "Backfill strategy selector (currently only backfill).",
		},
		{
			Name:         "INGESTOR_BACKFILL_PAGE_LIMIT",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "500",
			Description:  "Page size used by backfill fetches.",
		},
		{
			Name:         "INGESTOR_BACKFILL_SINCE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "Optional inclusive lower timestamp bound for backfill.",
		},
		{
			Name:         "INGESTOR_BACKFILL_UNTIL",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "Optional inclusive upper timestamp bound for backfill.",
		},
		{
			Name:         "INGESTOR_FILTER_GROUP",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "default_v1",
			Description:  "Active relay filter group name.",
		},
		{
			Name:         "INGESTOR_FILTER_GROUPS_JSON",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "Optional JSON map of relay filter groups; `default_v1` remains required and must keep the built-in live-ingest kind set.",
		},
		{
			Name:         "INGESTOR_LIVE_BOOTSTRAP_LOOKBACK_SECONDS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "300",
			Description:  "Live mode lookback window in seconds before tailing.",
		},
		{
			Name:         "INGESTOR_LIVE_RESUME_OVERLAP_SECONDS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "60",
			Description:  "Live mode overlap window in seconds for resume safety.",
		},
		{
			Name:         "INGESTOR_MODE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "live",
			Description:  "Ingestor runtime mode (live or replay).",
		},
		{
			Name:         "INGESTOR_RELAY_ALLOWLIST",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "Allowed relay URLs. Required when INGESTOR_RELAY_URLS is set.",
		},
		{
			Name:         "INGESTOR_RELAY_BACKOFF_INITIAL",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "1s",
			Description:  "Initial reconnect backoff for relay connections.",
		},
		{
			Name:         "INGESTOR_RELAY_BACKOFF_MAX",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "30s",
			Description:  "Maximum reconnect backoff for relay connections.",
		},
		{
			Name:         "INGESTOR_RELAY_CONNECT_TIMEOUT",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "10s",
			Description:  "Connection timeout for relay sessions.",
		},
		{
			Name:         "INGESTOR_RELAY_DISABLED",
			Runtimes:     []string{"api", "ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "CSV list of allowlisted relay URLs to disable.",
		},
		{
			Name:         "INGESTOR_RELAY_LAG_THRESHOLD",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "45s",
			Description:  "Lag threshold used for relay health reporting.",
		},
		{
			Name:         "INGESTOR_RELAY_REQUIRE_TLS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "true (non-local env), false (local env)",
			Description:  "Require wss:// relay URLs when enabled.",
		},
		{
			Name:         "INGESTOR_RELAY_URLS",
			Runtimes:     []string{"api", "ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "CSV list of relay URLs (required for INGESTOR_MODE=live).",
		},
		{
			Name:         "INGESTOR_REPLAY_FIXTURE_PATH",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "Replay fixture path (required for INGESTOR_MODE=replay).",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_COOLDOWN",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "30m",
			Description:  "Cooldown between successful trust-targeted fetches for the same pubkey.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_ENABLED",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Enable bounded trust-targeted pubkey fetch scheduling.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_MAX_PROMOTIONS_PER_CYCLE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "50",
			Description:  "Maximum frontier/suggestion promotions allowed per scheduler cycle.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_MAX_SELECTED_PER_CYCLE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "100",
			Description:  "Maximum trust frontier pubkeys selected for targeted fetch per cycle.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_MAX_TRACKED_PUBKEYS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "5000",
			Description:  "Maximum trust-ranked pubkeys maintained in the ingest frontier.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_PAGE_LIMIT_PER_RELAY",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "200",
			Description:  "Per-relay page size for trust-targeted pubkey fetch requests.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_RECENT_LOOKBACK_SECONDS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "86400",
			Description:  "Recent history lookback window in seconds for targeted pubkey fetches.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_REFRESH_INTERVAL",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "2m",
			Description:  "Scheduler interval for trust frontier refresh and targeted fetch cycles.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_RETRY_DELAY",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "10m",
			Description:  "Delay before retrying a pubkey after targeted fetch errors.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_STABLE_WINDOW",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "10m",
			Description:  "Minimum stability window before newly seen trust candidates become active.",
		},
		{
			Name:         "INGESTOR_TRUST_GATE_MAX_HOPS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "2",
			Description:  "Maximum trust-graph hop distance from a seed for an author to be considered trusted by the live ingest gate.",
		},
		{
			Name:         "INGESTOR_TRUST_GATE_MODE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "open",
			Description:  "Trust-bounded ingest gate mode: open (shadow, record metrics only) or trusted_only (enforce author trust for kinds 1/4/9802/10000/10003/30023 and 6/7/9735 target-exists).",
		},
		{
			Name:         "INGESTOR_TRUST_GATE_REFRESH_INTERVAL",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "2m",
			Description:  "Interval between refreshes of the in-memory trusted-author set loaded from trust_graph_snapshot.",
		},
		{
			Name:         "INGESTOR_TRUST_PRIORITIZATION_ENABLED",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable trust-driven relay ordering for ingestor startup ordering.",
		},
		{
			Name:         "INGESTOR_TRUST_PRIORITIZATION_TOP_PUBKEYS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum top trust pubkeys considered for relay ordering.",
		},

		// Relay Registry
		{
			Name:         "RELAY_REGISTRY_ENABLED",
			Runtimes:     []string{"ingestor", "worker"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Enable the dynamic relay registry subsystem.",
		},
		{
			Name:         "RELAY_REGISTRY_SEED_RELAYS",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "",
			Description:  "Comma-separated list of seed relay URLs to bootstrap the registry.",
		},
		{
			Name:         "RELAY_REGISTRY_ALLOW_PRIVATE_NETWORK",
			Runtimes:     []string{"ingestor", "worker"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Allow private/local network addresses in relay URLs.",
		},
		{
			Name:         "RELAY_REGISTRY_REFRESH_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "5m",
			Description:  "Interval between relay registry refresh cycles.",
		},
		{
			Name:         "RELAY_REGISTRY_DISCOVERY_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Enable relay discovery from user relay lists.",
		},
		{
			Name:         "RELAY_REGISTRY_DISCOVERY_MIN_DISTINCT_USER_REFS",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "3",
			Description:  "Minimum distinct user references required to consider a relay candidate.",
		},
		{
			Name:         "RELAY_REGISTRY_DISCOVERY_MAX_NEW_CANDIDATES",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "25",
			Description:  "Maximum new candidate relays to add per discovery run.",
		},
		{
			Name:         "RELAY_REGISTRY_PROBING_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Enable periodic relay health probing.",
		},
		{
			Name:         "RELAY_REGISTRY_PROBING_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "5m",
			Description:  "Interval between probe cycles.",
		},
		{
			Name:         "RELAY_REGISTRY_PROBING_TIMEOUT_CONNECT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "10s",
			Description:  "Websocket connect timeout for relay probes.",
		},
		{
			Name:         "RELAY_REGISTRY_PROBING_TIMEOUT_EOSE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "15s",
			Description:  "EOSE wait timeout for relay probes.",
		},
		{
			Name:         "RELAY_REGISTRY_PROBING_MAX_PARALLEL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "5",
			Description:  "Maximum parallel probe goroutines.",
		},
		{
			Name:         "RELAY_REGISTRY_ADMISSION_MAX_TOTAL_ACTIVE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "15",
			Description:  "Hard cap on total active relays (pinned + dynamic).",
		},
		{
			Name:         "RELAY_REGISTRY_ADMISSION_MAX_DYNAMIC_ACTIVE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "10",
			Description:  "Hard cap on dynamically admitted active relays.",
		},
		{
			Name:         "RELAY_REGISTRY_ADMISSION_MAX_PROBATION",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "20",
			Description:  "Hard cap on relays in probation state.",
		},
		{
			Name:         "RELAY_REGISTRY_RETENTION_RAW_PROBE_DAYS",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "14",
			Description:  "Days to retain raw probe observation rows.",
		},
		{
			Name:         "RELAY_REGISTRY_RETENTION_PURGE_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "500",
			Description:  "Maximum rows to delete per probe observation retention purge cycle.",
		},
		{
			Name:         "RELAY_REGISTRY_RETENTION_PURGE_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "1h",
			Description:  "Interval between probe observation retention purge cycles.",
		},
		{
			Name:         "RELAY_REGISTRY_ADMISSION_MIN_SCORE_PROBATION",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "10",
			Description:  "Minimum score for a candidate to enter probation.",
		},
		{
			Name:         "RELAY_REGISTRY_ADMISSION_MIN_SCORE_ACTIVE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "30",
			Description:  "Minimum score for a probation relay to become active.",
		},
		{
			Name:         "RELAY_REGISTRY_ADMISSION_DEMOTE_FAILURE_THRESHOLD",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "60",
			Description:  "Probe failure rate percentage above which an active relay is demoted (e.g. 60 = 60%).",
		},
		{
			Name:         "RELAY_REGISTRY_RECONCILE_POLL_INTERVAL",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "30s",
			Description:  "How often the ingestor polls for desired relay set changes.",
		},
		{
			Name:         "RELAY_REGISTRY_RECONCILE_DRAIN_TIMEOUT",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "10s",
			Description:  "Grace period before disconnecting a relay removed from the desired set.",
		},
		{
			Name:         "INGESTOR_ACCOUNT_OBSERVATION_ENABLED",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable counts-only observation accounting: buffer seen pubkeys in memory and batch account_states observed_count UPSERTs out-of-band.",
		},
		{
			Name:         "INGESTOR_ACCOUNT_OBSERVATION_FLUSH_INTERVAL",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "10s",
			Description:  "How often the in-memory observation buffer is flushed to account_states.",
		},
		{
			Name:         "INGESTOR_ACCOUNT_OBSERVATION_MAX_BUFFER_KEYS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "100000",
			Description:  "Cap on distinct pubkeys buffered between flushes (bounds memory under a flood; excess new pubkeys are dropped until the next flush).",
		},
	}
}
