package config

func configEnvDocsShared() []EnvVarDoc {
	return []EnvVarDoc{
		{
			Name:         "DATABASE_URL",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     true,
			DefaultValue: "",
			Description:  "PostgreSQL connection string.",
		},
		{
			Name:         "DATABASE_MAX_CONNS",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "0",
			Description:  "Override pgxpool max connections; when > 0, takes precedence over pool_max_conns parsed from DATABASE_URL. The pgx default of 4 is dangerously low for the worker process which runs the bundle pool plus several background sweeper goroutines (author_analytics, profile_stats, meilisearch); with the default pool the sweepers' multi-second aggregate queries monopolize all connections and block bundle workers indefinitely.",
		},
		{
			Name:         "DEBUG_ADDR",
			Runtimes:     []string{"api", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "",
			Description:  "Optional debug/pprof listen address. Leave empty by default; prefer localhost binding.",
		},
		{
			Name:         "ENVIRONMENT",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "development",
			Description:  "Deployment environment label.",
		},
		{
			Name:         "METRICS_ADDR",
			Runtimes:     []string{"ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: ":9090",
			Description:  "Prometheus metrics listen address for ingestor, worker, and trust_worker. API exposes /metrics on HTTP_ADDR.",
		},
		{
			Name:         "TRUST_CANONICAL_INGEST_MODE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "open",
			Description:  "Trust policy mode for canonical ingest candidates: open (ignore trust), prefer_trusted (bias toward trusted), trusted_only (allow trusted set only). Default stays open to preserve current ingest behavior.",
		},
		{
			Name:         "TRUST_SURFACE_POLICY_PRESET",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "",
			Description:  "Optional preset for public discovery/search surfaces: open (all open), balanced (prefer_trusted for discovery/search/fallback), strict (trusted_only for discovery/search/fallback). Per-surface TRUST_*_MODE env vars still override this preset when set.",
		},
		{
			Name:         "TRUST_DISCOVERY_CANDIDATE_MODE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "open",
			Description:  "Trust policy mode for discovery candidate selection: open, prefer_trusted, or trusted_only.",
		},
		{
			Name:         "TRUST_FALLBACK_FETCH_MODE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "open",
			Description:  "Trust policy mode for relay fallback fetches: open, prefer_trusted, or trusted_only.",
		},
		{
			Name:         "TRUST_FALLBACK_FETCH_MAX_ATTEMPTS",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "1",
			Description:  "Maximum bounded fallback attempts per entity lookup before giving up.",
		},
		{
			Name:         "TRUST_FALLBACK_FETCH_MAX_RELAYS_PER_ATTEMPT",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "3",
			Description:  "Maximum relay fanout permitted for each fallback attempt.",
		},
		{
			Name:         "TRUST_FALLBACK_FETCH_MAX_TIME_BUDGET",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "2s",
			Description:  "Total fallback time budget per lookup before fallback stops.",
		},
		{
			Name:         "TRUST_FALLBACK_FETCH_ALLOW_DIRECT_LOOKUP",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Allow explicitly referenced direct lookups to use strict fallback even in trusted_only mode.",
		},
		{
			Name:         "TRUST_MAX_HOPS",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "3",
			Description:  "Maximum trust-graph expansion depth used by trust-aware policy surfaces.",
		},
		{
			Name:         "TRUST_MINIMUM_SCORE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "0",
			Description:  "Minimum trust score threshold used by trust-aware policy surfaces.",
		},
		{
			Name:         "TRUST_REFRESH_INTERVAL",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "10m",
			Description:  "Refresh cadence for trust policy inputs (seed graph and score snapshots).",
		},
		{
			Name:         "TRUST_RETENTION_POLICY_MODE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "open",
			Description:  "Optional trust policy mode for retention hooks: open, prefer_trusted, or trusted_only.",
		},
		{
			Name:         "TRUST_RETENTION_DISCOVERY_CACHE_ENABLED",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable trust-aware retention hook parameters for discovery cache TTL shaping.",
		},
		{
			Name:         "TRUST_RETENTION_DISCOVERY_CACHE_TRUSTED_TTL",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "10m0s",
			Description:  "Retention horizon for trusted discovery cache rows.",
		},
		{
			Name:         "TRUST_RETENTION_DISCOVERY_CACHE_UNTRUSTED_TTL",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "2m0s",
			Description:  "Retention horizon for untrusted discovery cache rows (should be <= trusted TTL).",
		},
		{
			Name:         "TRUST_RETENTION_DISCOVERY_CANDIDATE_ENABLED",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable trust-aware retention hook parameters for derived discovery/ranking candidates.",
		},
		{
			Name:         "TRUST_RETENTION_DISCOVERY_CANDIDATE_TRUSTED_MAX_AGE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "24h0m0s",
			Description:  "Retention horizon for trusted derived discovery/ranking candidates.",
		},
		{
			Name:         "TRUST_RETENTION_DISCOVERY_CANDIDATE_UNTRUSTED_MAX_AGE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "6h0m0s",
			Description:  "Retention horizon for untrusted derived discovery/ranking candidates (should be <= trusted horizon).",
		},
		{
			Name:         "TRUST_RETENTION_ENRICHMENT_STATE_ENABLED",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Enable trust-aware retention hook parameters for optional low-value enrichment state.",
		},
		{
			Name:         "TRUST_RETENTION_ENRICHMENT_STATE_TRUSTED_MAX_AGE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "12h0m0s",
			Description:  "Retention horizon for trusted optional low-value enrichment state.",
		},
		{
			Name:         "TRUST_RETENTION_ENRICHMENT_STATE_UNTRUSTED_MAX_AGE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "3h0m0s",
			Description:  "Retention horizon for untrusted optional low-value enrichment state (should be <= trusted horizon).",
		},
		{
			Name:         "TRUST_RETENTION_FALLBACK_METADATA_ENABLED",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Enable trust-aware retention hook parameters for optional transient fallback metadata.",
		},
		{
			Name:         "TRUST_RETENTION_FALLBACK_METADATA_TRUSTED_MAX_AGE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "2h0m0s",
			Description:  "Retention horizon for trusted transient fallback metadata.",
		},
		{
			Name:         "TRUST_RETENTION_FALLBACK_METADATA_UNTRUSTED_MAX_AGE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "30m0s",
			Description:  "Retention horizon for untrusted transient fallback metadata (should be <= trusted horizon).",
		},
		{
			Name:         "TRUST_SEARCH_RANKING_MODE",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "prefer_trusted",
			Description:  "Trust policy mode for search ranking inputs: open, prefer_trusted, or trusted_only.",
		},
		{
			Name:         "TRUST_SEED_PUBKEYS",
			Runtimes:     []string{"api", "ingestor", "trust_worker", "worker"},
			Required:     false,
			DefaultValue: "",
			Description:  "CSV trust seed pubkeys used as trust graph roots. Required when any trust mode is trusted_only.",
		},
	}
}
