package config

func configEnvDocsAPI() []EnvVarDoc {
	return []EnvVarDoc{
		{
			Name:         "ADMIN_BEARER_TOKEN",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "",
			Description:  "Optional bearer token for admin HTTP endpoints.",
		},
		{
			Name:         "API_MAX_BATCH_SIZE",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "200",
			Description:  "Maximum IDs accepted by batch event/profile API requests.",
		},
		{
			Name:         "API_DISCOVERY_CACHE_ENABLED",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable short-TTL response caching for public discovery trending and stats endpoints.",
		},
		{
			Name:         "API_DISCOVERY_CACHE_MAX_ENTRIES",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "256",
			Description:  "Maximum in-memory entries retained by discovery/stats response cache.",
		},
		{
			Name:         "API_DISCOVERY_CACHE_BUNDLE_TTL",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "60s",
			Description:  "TTL for cached homepage/public bundle responses.",
		},
		{
			Name:         "API_DISCOVERY_CACHE_DISCOVERY_TTL",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "60s",
			Description:  "TTL for cached public discovery responses (trending and discovery detail endpoints).",
		},
		{
			Name:         "API_DISCOVERY_CACHE_SUGGESTION_TTL",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "60s",
			Description:  "TTL for cached public suggestion responses.",
		},
		{
			Name:         "API_DISCOVERY_CACHE_STATS_TTL",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "10m",
			Description:  "TTL for cached public stats responses.",
		},
		{
			Name:         "API_DISCOVERY_CACHE_PUBLIC_STATS_TTL",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "10m",
			Description:  "Compatibility alias for API_DISCOVERY_CACHE_STATS_TTL.",
		},
		{
			Name:         "API_DISCOVERY_CACHE_TRENDING_TTL",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "60s",
			Description:  "Compatibility alias for bundle/discovery/suggestion TTL defaults.",
		},
		{
			Name:         "API_RELAY_FALLBACK_ENABLED",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Enable best-effort relay fallback for local event/profile misses.",
		},
		{
			Name:         "API_RELAY_FALLBACK_MAX_FANOUT",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "3",
			Description:  "Maximum number of fallback relays queried per lookup.",
		},
		{
			Name:         "API_RELAY_FALLBACK_TIMEOUT",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "2s",
			Description:  "Per-relay timeout budget for fallback lookups.",
		},
		{
			Name:         "API_RELAY_FALLBACK_URLS",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "",
			Description:  "CSV fallback relay URLs. If empty, API falls back to INGESTOR_RELAY_URLS.",
		},
		{
			Name:         "HTTP_ADDR",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: ":8080",
			Description:  "HTTP listen address for the API server.",
		},
		{
			Name:         "HTTP_BATCH_RATE_LIMIT_RPM",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "40",
			Description:  "Per-IP requests per minute for HTTP batch endpoints.",
		},
		{
			Name:         "HTTP_DISCOVERY_RATE_LIMIT_RPM",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "90",
			Description:  "Per-IP requests per minute for public discovery endpoints.",
		},
		{
			Name:         "HTTP_DM_COMPAT_RATE_LIMIT_RPM",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "30",
			Description:  "Per-connection requests per minute for DM compatibility calls on the Primal WebSocket gateway.",
		},
		{
			Name:         "HTTP_RATE_LIMIT_BURST",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "60",
			Description:  "Burst size for the default HTTP rate limiter.",
		},
		{
			Name:         "HTTP_RATE_LIMIT_RPM",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "240",
			Description:  "Per-IP requests per minute for default HTTP routes.",
		},
		{
			Name:         "HTTP_PUBLIC_MAX_DISCOVERY_WINDOW_HOURS",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "720",
			Description:  "Maximum discovery/public stats window size in hours for guarded query params.",
		},
		{
			Name:         "HTTP_PUBLIC_MAX_PAGE_OFFSET",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "5000",
			Description:  "Maximum offset accepted by guarded public pagination endpoints.",
		},
		{
			Name:         "HTTP_PUBLIC_MAX_PAGE_SIZE",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "100",
			Description:  "Maximum page size accepted by guarded public pagination endpoints.",
		},
		{
			Name:         "HTTP_PUBLIC_MAX_RESULT_LIMIT",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "100",
			Description:  "Maximum result limit accepted by guarded public discovery/search endpoints.",
		},
		{
			Name:         "HTTP_PUBLIC_MAX_SEARCH_WINDOW_HOURS",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "168",
			Description:  "Maximum search window size in hours for guarded query params.",
		},
		{
			Name:         "HTTP_PUBLIC_STATS_RATE_LIMIT_RPM",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "120",
			Description:  "Per-IP requests per minute for public stats endpoints.",
		},
		{
			Name:         "HTTP_SEARCH_RATE_LIMIT_RPM",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "60",
			Description:  "Per-IP requests per minute for the search endpoint.",
		},
		{
			Name:         "HTTP_SUGGEST_RATE_LIMIT_RPM",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "120",
			Description:  "Per-IP requests per minute for public suggestion endpoints.",
		},
		{
			Name:         "PRIMAL_WS_ALLOWED_ORIGINS",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "",
			Description:  "CSV allowlist of browser origins for Primal WS.",
		},
		{
			Name:         "PRIMAL_WS_ALLOW_ANY_ORIGIN",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Allow all WS origins, bypassing PRIMAL_WS_ALLOWED_ORIGINS validation.",
		},
		{
			Name:         "PRIMAL_WS_MAX_MESSAGE_BYTES",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "1048576",
			Description:  "Maximum inbound WebSocket message size in bytes.",
		},
		{
			Name:         "PRIMAL_WS_MAX_REQ_PER_MINUTE",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "240",
			Description:  "Per-connection request rate limit for Primal WebSocket REQ calls.",
		},
		{
			Name:         "PRIMAL_WS_MAX_SUBSCRIPTIONS",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "200",
			Description:  "Maximum concurrent Primal WS subscriptions per connection.",
		},
		{
			Name:         "PRIMAL_WS_REQUEST_TIMEOUT",
			Runtimes:     []string{"api"},
			Required:     false,
			DefaultValue: "10s",
			Description:  "Timeout for individual Primal WS request handling.",
		},
	}
}
