package config

func configEnvDocsWorker() []EnvVarDoc {
	return []EnvVarDoc{
		{
			Name:         "WORKER_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "4",
			Description:  "Worker goroutine concurrency for the default job pool (legacy / backlog work).",
		},
		{
			Name:         "WORKER_LIVE_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "WORKER_CONCURRENCY",
			Description:  "Worker goroutine concurrency for the live job pool (events from real-time relay subscriptions). Set to 0 to disable.",
		},
		{
			Name:         "WORKER_BACKFILL_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "WORKER_CONCURRENCY",
			Description:  "Worker goroutine concurrency for the backfill job pool (events from historical fetch / trust fetch / metadata discovery). Set to 0 to disable.",
		},
		{
			Name:         "WORKER_CLAIM_BATCH_SIZE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "10",
			Description:  "Maximum number of jobs claimed per claim-loop iteration for each worker pool.",
		},
		{
			Name:         "WORKER_AUTHOR_ANALYTICS_SWEEPER_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable the background sweeper that drains pending_author_analytics_recomputes (per-author analytics rebuilds deferred from derive_event_bundle).",
		},
		{
			Name:         "WORKER_AUTHOR_ANALYTICS_SWEEPER_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "5s",
			Description:  "Polling interval between author-analytics sweeper batches when the dirty queue is empty. Sweepers loop without sleeping while batches are full.",
		},
		{
			Name:         "WORKER_AUTHOR_ANALYTICS_SWEEPER_BATCH_SIZE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "25",
			Description:  "Maximum dirty pubkeys claimed and rebuilt per author-analytics sweeper batch.",
		},
		{
			Name:         "WORKER_AUTHOR_ANALYTICS_SWEEPER_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "4",
			Description:  "Number of concurrent author-analytics sweeper goroutines. Each independently claims dirty pubkeys via FOR UPDATE SKIP LOCKED.",
		},
		{
			Name:         "WORKER_AUTHOR_ANALYTICS_WINDOWS_DAYS",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "7,30",
			Description:  "Comma-separated window_days values the live author-analytics rebuild aggregates. Schema permits {7, 30, 90}; the default omits 90 because each window roughly doubles per-pubkey rebuild cost. Set to 7,30,90 to refresh the 90d window in real time at the cost of throughput.",
		},
		{
			Name:         "WORKER_AUTHOR_ANALYTICS_REBUILD_TIMEOUT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "90s",
			Description:  "Maximum time a single per-pubkey author-analytics rebuild may hold its transaction (and therefore its pgxpool connection). On timeout the transaction rolls back, the per-pubkey advisory lock auto-releases, and the pubkey is retried on the next sweeper cycle. Safety net against any single hot pubkey monopolizing a connection long enough to starve bundle workers.",
		},
		{
			Name:         "WORKER_PROFILE_STATS_SWEEPER_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable the background sweeper that drains pending_profile_stats_recomputes (per-pubkey ProjectProfilePublicStats and ProjectProfileDiscoveryStats recomputes deferred from derive_event_bundle).",
		},
		{
			Name:         "WORKER_PROFILE_STATS_SWEEPER_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "5s",
			Description:  "Polling interval between profile-stats sweeper batches when the dirty queue is empty. Sweepers loop without sleeping while batches are full.",
		},
		{
			Name:         "WORKER_PROFILE_STATS_SWEEPER_BATCH_SIZE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "25",
			Description:  "Maximum dirty pubkeys claimed and recomputed per profile-stats sweeper batch.",
		},
		{
			Name:         "WORKER_PROFILE_STATS_SWEEPER_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "4",
			Description:  "Number of concurrent profile-stats sweeper goroutines. Each independently claims dirty pubkeys via FOR UPDATE SKIP LOCKED.",
		},
		{
			Name:         "WORKER_MEILISEARCH_SWEEPER_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable the background sweeper that drains pending_meilisearch_syncs (per-event Meilisearch index syncs deferred from derive_event_bundle). Has no effect when MEILI_ENABLED=false.",
		},
		{
			Name:         "WORKER_MEILISEARCH_SWEEPER_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "2s",
			Description:  "Polling interval between Meilisearch sweeper batches when the dirty queue is empty. Sweepers loop without sleeping while batches are full.",
		},
		{
			Name:         "WORKER_MEILISEARCH_SWEEPER_BATCH_SIZE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "50",
			Description:  "Maximum dirty events claimed and synced to Meilisearch per sweeper batch.",
		},
		{
			Name:         "WORKER_MEILISEARCH_SWEEPER_CONCURRENCY",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "4",
			Description:  "Number of concurrent Meilisearch sweeper goroutines. Each independently claims dirty events via FOR UPDATE SKIP LOCKED.",
		},
		{
			Name:         "WORKER_JOB_RUNNING_TIMEOUT",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "15m0s",
			Description:  "Lease timeout for running jobs before stale recovery treats them as orphaned.",
		},
		{
			Name:         "WORKER_JOB_STALE_RECOVERY_BATCH_LIMIT",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "100",
			Description:  "Maximum stale running jobs processed per recovery interval.",
		},
		{
			Name:         "WORKER_JOB_STALE_RECOVERY_INTERVAL",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "30s",
			Description:  "Interval between stale running-job recovery scans.",
		},
		{
			Name:         "WORKER_JOB_RETENTION_DEAD_MAX_AGE",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "336h0m0s",
			Description:  "Max age for dead jobs (purged by finished_at) before retention purges terminal history.",
		},
		{
			Name:         "WORKER_JOB_RETENTION_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum terminal jobs deleted per retention purge run.",
		},
		{
			Name:         "WORKER_JOB_RETENTION_ENABLED",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable periodic retention purge of terminal job history. Applied independently in each worker process.",
		},
		{
			Name:         "WORKER_JOB_RETENTION_RUN_INTERVAL",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "15m0s",
			Description:  "Interval between terminal job retention purge runs.",
		},
		{
			Name:         "WORKER_JOB_RETENTION_SUCCEEDED_MAX_AGE",
			Runtimes:     []string{"trust_worker", "worker"},
			Required:     false,
			DefaultValue: "24h0m0s",
			Description:  "Max age for succeeded jobs (purged by finished_at) before retention purges terminal history.",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_PAYLOAD_TRIM_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "500",
			Description:  "Maximum invalid_events rows with raw_payload trimmed to NULL per retention run when payload trimming is enabled.",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_PAYLOAD_TRIM_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable optional second-stage invalid_events payload trimming (raw_payload set to NULL before full-row retention purge).",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_PAYLOAD_TRIM_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "168h0m0s",
			Description:  "Max age for invalid_events rows before payload-only trimming (must be smaller than WORKER_INVALID_EVENTS_RETENTION_MAX_AGE).",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_RETENTION_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "500",
			Description:  "Maximum invalid_events rows deleted per retention purge run.",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_RETENTION_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable periodic invalid_events retention purge.",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_RETENTION_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "720h0m0s",
			Description:  "Max age for invalid_events rows before retention purge.",
		},
		{
			Name:         "WORKER_INVALID_EVENTS_RETENTION_RUN_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "1h0m0s",
			Description:  "Interval between invalid_events retention purge runs.",
		},
		{
			Name:         "WORKER_RETENTION_DELETION_DEAD_GRACE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "168h0m0s",
			Description:  "Derivation-safety grace window: a dead derive_event_bundle job only blocks purge of its deletion event while updated within this window. Past it, a permanently-dead derivation no longer blocks cleanup.",
		},
		{
			Name:         "WORKER_RETENTION_DELETION_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum raw deletion events (kind 5) deleted per retention purge batch.",
		},
		{
			Name:         "WORKER_RETENTION_DELETION_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable periodic retention purge of processed raw deletion events (kind 5). The distilled deletion_events tombstone ledger survives; only the raw rows and cascade-cleaned tags/references are removed.",
		},
		{
			Name:         "WORKER_RETENTION_DELETION_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "336h0m0s",
			Description:  "Age (by event created_at) beyond which processed raw deletion events become eligible for retention purge.",
		},
		{
			Name:         "WORKER_RETENTION_DELETION_RUN_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "1h0m0s",
			Description:  "Interval between deletion-events retention purge runs.",
		},
		{
			Name:         "WORKER_RETENTION_ENGAGEMENT_DEAD_GRACE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "168h0m0s",
			Description:  "Derivation-safety grace window: a dead derive_event_bundle job only blocks purge of its engagement event while updated within this window. Past it, a permanently-dead derivation no longer blocks cleanup.",
		},
		{
			Name:         "WORKER_RETENTION_ENGAGEMENT_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum raw engagement events (kinds 6/7/9735) deleted per retention purge batch.",
		},
		{
			Name:         "WORKER_RETENTION_ENGAGEMENT_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable periodic retention purge of raw engagement events (kinds 6/7/9735). Lifetime aggregate counters survive; only raw rows and cascade-cleaned contributions are removed.",
		},
		{
			Name:         "WORKER_RETENTION_ENGAGEMENT_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "336h0m0s",
			Description:  "Age (by event created_at) beyond which raw engagement events become eligible for retention purge.",
		},
		{
			Name:         "WORKER_RETENTION_ENGAGEMENT_RUN_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "1h0m0s",
			Description:  "Interval between engagement-events retention purge runs.",
		},
		{
			Name:         "WORKER_RETENTION_REPLACEABLE_DEAD_GRACE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "168h0m0s",
			Description:  "Derivation-safety grace window: a dead derive_event_bundle job only blocks purge of its superseded replaceable event while updated within this window. Past it, a permanently-dead derivation no longer blocks cleanup.",
		},
		{
			Name:         "WORKER_RETENTION_REPLACEABLE_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum superseded replaceable events (kinds 0/3/10000/10002/10003 and parameterized 30023) deleted per retention purge batch.",
		},
		{
			Name:         "WORKER_RETENTION_REPLACEABLE_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable periodic retention purge of superseded raw replaceable events (kinds 0/3/10000/10002/10003 and parameterized 30023). Only versions strictly older than the current winner are removed; latest-version projections (contact_lists_latest, relay_lists_latest, profiles_latest, replaceable_state) survive.",
		},
		{
			Name:         "WORKER_RETENTION_REPLACEABLE_MIN_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "24h0m0s",
			Description:  "Stability window (by events.first_seen_at) a superseded replaceable version must reach before it becomes eligible for retention purge.",
		},
		{
			Name:         "WORKER_RETENTION_REPLACEABLE_RUN_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "1h0m0s",
			Description:  "Interval between superseded-replaceable retention purge runs.",
		},
		{
			Name:         "WORKER_ACCOUNT_STATE_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable the derived account-state recompute loop (recomputes lifecycle state from trust/observation/profile signals and records transitions).",
		},
		{
			Name:         "WORKER_ACCOUNT_STATE_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "1m0s",
			Description:  "Interval between account-state recompute cycles.",
		},
		{
			Name:         "WORKER_ACCOUNT_STATE_BATCH_SIZE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "500",
			Description:  "Number of accounts recomputed per cycle (oldest-updated first).",
		},
		{
			Name:         "WORKER_ACCOUNT_STATE_STALE_AFTER",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "15m0s",
			Description:  "Only accounts whose state is older than this are recomputed each cycle.",
		},
		{
			Name:         "WORKER_ACCOUNT_STATE_TRANSITION_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "720h0m0s",
			Description:  "Retention horizon for the append-only account_state_transitions audit table.",
		},
		{
			Name:         "HYDRATION_ENABLED",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable the on-demand account hydration feature (job handler on the worker and the trigger endpoints on the API).",
		},
		{
			Name:         "HYDRATION_PUBLIC_ENABLED",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Allow unauthenticated, rate-limited public triggering of hydration via POST /api/v1/accounts/{pubkey}/hydrate.",
		},
		{
			Name:         "HYDRATION_MAX_RELAYS",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "8",
			Description:  "Maximum relays queried during a single hydration run.",
		},
		{
			Name:         "HYDRATION_MAX_EVENTS_PER_ACCOUNT",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum events persisted per hydration run.",
		},
		{
			Name:         "HYDRATION_MAX_LOOKBACK_DAYS",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "90",
			Description:  "How far back authored notes are fetched during hydration; also the full-coverage window for completeness.",
		},
		{
			Name:         "HYDRATION_MAX_RUNTIME",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "1m0s",
			Description:  "Wall-clock cap for a single hydration run.",
		},
		{
			Name:         "HYDRATION_MAX_BYTES",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "33554432",
			Description:  "Soft byte budget for a single hydration run (0 = unbounded by bytes).",
		},
		{
			Name:         "HYDRATION_COOLDOWN",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "6h0m0s",
			Description:  "Minimum interval between successive hydrations of the same account.",
		},
		{
			Name:         "HYDRATION_MAX_CONCURRENCY",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "2",
			Description:  "Maximum simultaneous hydration runs on the worker.",
		},
		{
			Name:         "HYDRATION_RATE_LIMIT",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "10",
			Description:  "Per-minute cap on public-triggered hydration enqueues.",
		},
		{
			Name:         "HYDRATION_RELAYS",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "",
			Description:  "CSV explicit relay set for hydration. When empty the worker falls back to the most recently active relays known locally.",
		},
		{
			Name:         "HYDRATION_CONNECT_TIMEOUT",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "10s",
			Description:  "Per-relay websocket connect timeout during hydration.",
		},
		{
			Name:         "HYDRATION_IDLE_TIMEOUT",
			Runtimes:     []string{"api", "worker"},
			Required:     false,
			DefaultValue: "4s",
			Description:  "Per-relay idle timeout (no frames) before a hydration fetch concludes.",
		},
		{
			Name:         "WORKER_RETENTION_UNTRUSTED_AUTHOR_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable retention purge of author-gated raw events (kinds 1/4/9802/10000/10003/30023) whose author is outside trust_graph_snapshot. Fail-safe: deletes nothing while the trust graph snapshot is empty.",
		},
		{
			Name:         "WORKER_RETENTION_UNTRUSTED_AUTHOR_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "336h0m0s",
			Description:  "Age beyond which untrusted-author events become eligible for purge; enforced on both created_at and first_seen_at so freshly backfilled events are never purged early. Deliberately short (14d) because with the default open ingest gate this horizon is what bounds steady-state disk usage.",
		},
		{
			Name:         "WORKER_RETENTION_UNTRUSTED_AUTHOR_DEAD_GRACE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "168h0m0s",
			Description:  "Derivation-safety grace window: a dead derive_event_bundle job only blocks purge of its untrusted-author event while updated within this window.",
		},
		{
			Name:         "WORKER_RETENTION_UNTRUSTED_AUTHOR_RUN_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "1h0m0s",
			Description:  "How often the untrusted-author retention loop runs.",
		},
		{
			Name:         "WORKER_RETENTION_UNTRUSTED_AUTHOR_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum untrusted-author events deleted per retention purge batch.",
		},
		{
			Name:         "WORKER_RETENTION_AUTHOR_RECENT_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable retention pruning of the author_recent_events projection (age horizon plus per-author cap). The projection is rebuildable from canonical events.",
		},
		{
			Name:         "WORKER_RETENTION_AUTHOR_RECENT_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "2160h0m0s",
			Description:  "Age (by event created_at) beyond which author_recent_events rows are pruned.",
		},
		{
			Name:         "WORKER_RETENTION_AUTHOR_RECENT_PER_AUTHOR_CAP",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "200",
			Description:  "Maximum author_recent_events rows retained per author (newest first). Must be >= 100 because the API serves up to 100 recent events per request.",
		},
		{
			Name:         "WORKER_RETENTION_AUTHOR_RECENT_AUTHOR_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "500",
			Description:  "Maximum over-cap authors trimmed per cap pass, bounding the per-run aggregation work.",
		},
		{
			Name:         "WORKER_RETENTION_AUTHOR_RECENT_RUN_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "6h0m0s",
			Description:  "How often the author_recent_events retention loop runs.",
		},
		{
			Name:         "WORKER_RETENTION_AUTHOR_RECENT_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "5000",
			Description:  "Maximum author_recent_events rows deleted per prune batch (applies to the age and cap passes independently).",
		},
		{
			Name:         "WORKER_RETENTION_SEARCH_DOCS_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable search_documents grooming: stale note bodies are trimmed (the generated tsvector and GIN index shrink with them) and orphaned note documents are pruned.",
		},
		{
			Name:         "WORKER_RETENTION_SEARCH_DOCS_BODY_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "720h0m0s",
			Description:  "Freshness age beyond which note search-document bodies are trimmed to the configured prefix.",
		},
		{
			Name:         "WORKER_RETENTION_SEARCH_DOCS_BODY_MAX_CHARS",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "280",
			Description:  "Number of body characters retained when trimming stale note search documents.",
		},
		{
			Name:         "WORKER_RETENTION_SEARCH_DOCS_RUN_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "6h0m0s",
			Description:  "How often the search_documents grooming loop runs.",
		},
		{
			Name:         "WORKER_RETENTION_SEARCH_DOCS_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum search documents trimmed or pruned per grooming batch.",
		},
		{
			Name:         "WORKER_RETENTION_EVENT_RELAYS_ENABLED",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable pruning of duplicate event_relays provenance rows past the age horizon. The earliest-seen row per event always survives, so first-provenance is preserved forever.",
		},
		{
			Name:         "WORKER_RETENTION_EVENT_RELAYS_MAX_AGE",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "720h0m0s",
			Description:  "Age (by seen_at) beyond which non-first event_relays provenance rows are pruned. Relay window snapshots read at most 7d, so the 30d default keeps ample margin.",
		},
		{
			Name:         "WORKER_RETENTION_EVENT_RELAYS_RUN_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "6h0m0s",
			Description:  "How often the event_relays provenance retention loop runs.",
		},
		{
			Name:         "WORKER_RETENTION_EVENT_RELAYS_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "5000",
			Description:  "Maximum event_relays rows deleted per retention purge batch.",
		},
		{
			Name:         "TRUST_RETENTION_RUN_INTERVAL",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "1h0m0s",
			Description:  "How often the durable trust-retention hooks loop runs (stale trusted discovery candidates, idle low-value account_states rows). Per-scope enablement and horizons come from the TRUST_RETENTION_* hook envs.",
		},
		{
			Name:         "TRUST_RETENTION_DELETE_BATCH_LIMIT",
			Runtimes:     []string{"worker"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum rows deleted per trust-retention hook purge batch.",
		},
	}
}
