package config

func configEnvDocsIngestor() []EnvVarDoc {
	return []EnvVarDoc{
		{
			Name:         "INGESTOR_BACKFILL_CONNECT_TIMEOUT",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "10s",
			Description:  "Connection timeout used by backfill relay sessions.",
		},
		{
			Name:         "INGESTOR_BACKFILL_EMPTY_PAGE_MAX",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "2",
			Description:  "Maximum consecutive empty pages before backfill stops.",
		},
		{
			Name:         "INGESTOR_BACKFILL_ENABLED",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Enables bootstrap/backfill mode.",
		},
		{
			Name:         "INGESTOR_BACKFILL_IDLE_TIMEOUT",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "3s",
			Description:  "Idle timeout while waiting for backfill events.",
		},
		{
			Name:         "INGESTOR_BACKFILL_MODE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "backfill",
			Description:  "Backfill strategy selector (currently only backfill).",
		},
		{
			Name:         "INGESTOR_BACKFILL_PAGE_LIMIT",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "500",
			Description:  "Page size used by backfill fetches.",
		},
		{
			Name:         "INGESTOR_BACKFILL_SINCE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "Optional inclusive lower timestamp bound for backfill.",
		},
		{
			Name:         "INGESTOR_BACKFILL_UNTIL",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "Optional inclusive upper timestamp bound for backfill.",
		},
		{
			Name:         "INGESTOR_FILTER_GROUP",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "default_v1",
			Description:  "Active relay filter group name.",
		},
		{
			Name:         "INGESTOR_FILTER_GROUPS_JSON",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "Optional JSON map of relay filter groups; only `default_v1` is currently implemented for live ingest.",
		},
		{
			Name:         "INGESTOR_LIVE_BOOTSTRAP_LOOKBACK_SECONDS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "300",
			Description:  "Live mode lookback window in seconds before tailing.",
		},
		{
			Name:         "INGESTOR_LIVE_RESUME_OVERLAP_SECONDS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "60",
			Description:  "Live mode overlap window in seconds for resume safety.",
		},
		{
			Name:         "INGESTOR_MODE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "live",
			Description:  "Ingestor runtime mode (live or replay).",
		},
		{
			Name:         "INGESTOR_RELAY_ALLOWLIST",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "Allowed relay URLs. Required when INGESTOR_RELAY_URLS is set.",
		},
		{
			Name:         "INGESTOR_RELAY_BACKOFF_INITIAL",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "1s",
			Description:  "Initial reconnect backoff for relay connections.",
		},
		{
			Name:         "INGESTOR_RELAY_BACKOFF_MAX",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "30s",
			Description:  "Maximum reconnect backoff for relay connections.",
		},
		{
			Name:         "INGESTOR_RELAY_CONNECT_TIMEOUT",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "10s",
			Description:  "Connection timeout for relay sessions.",
		},
		{
			Name:         "INGESTOR_RELAY_DISABLED",
			Runtimes:     []string{"api", "ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "CSV list of allowlisted relay URLs to disable.",
		},
		{
			Name:         "INGESTOR_RELAY_LAG_THRESHOLD",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "45s",
			Description:  "Lag threshold used for relay health reporting.",
		},
		{
			Name:         "INGESTOR_RELAY_REQUIRE_TLS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "true (non-local env), false (local env)",
			Description:  "Require wss:// relay URLs when enabled.",
		},
		{
			Name:         "INGESTOR_RELAY_URLS",
			Runtimes:     []string{"api", "ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "CSV list of relay URLs (required for INGESTOR_MODE=live).",
		},
		{
			Name:         "INGESTOR_REPLAY_FIXTURE_PATH",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "",
			Description:  "Replay fixture path (required for INGESTOR_MODE=replay).",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_COOLDOWN",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "30m",
			Description:  "Cooldown between successful trust-targeted fetches for the same pubkey.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_ENABLED",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "false",
			Description:  "Enable bounded trust-targeted pubkey fetch scheduling.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_MAX_PROMOTIONS_PER_CYCLE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "50",
			Description:  "Maximum frontier/suggestion promotions allowed per scheduler cycle.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_MAX_SELECTED_PER_CYCLE",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "100",
			Description:  "Maximum trust frontier pubkeys selected for targeted fetch per cycle.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_MAX_TRACKED_PUBKEYS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "5000",
			Description:  "Maximum trust-ranked pubkeys maintained in the ingest frontier.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_PAGE_LIMIT_PER_RELAY",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "200",
			Description:  "Per-relay page size for trust-targeted pubkey fetch requests.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_RECENT_LOOKBACK_SECONDS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "86400",
			Description:  "Recent history lookback window in seconds for targeted pubkey fetches.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_REFRESH_INTERVAL",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "2m",
			Description:  "Scheduler interval for trust frontier refresh and targeted fetch cycles.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_RETRY_DELAY",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "10m",
			Description:  "Delay before retrying a pubkey after targeted fetch errors.",
		},
		{
			Name:         "INGESTOR_TRUST_FETCH_STABLE_WINDOW",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "10m",
			Description:  "Minimum stability window before newly seen trust candidates become active.",
		},
		{
			Name:         "INGESTOR_TRUST_PRIORITIZATION_ENABLED",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "true",
			Description:  "Enable trust-driven relay ordering for ingestor startup ordering.",
		},
		{
			Name:         "INGESTOR_TRUST_PRIORITIZATION_TOP_PUBKEYS",
			Runtimes:     []string{"ingestor"},
			Required:     false,
			DefaultValue: "2000",
			Description:  "Maximum top trust pubkeys considered for relay ordering.",
		},
	}
}
