// Package account owns the account-state bounded context: observation
// accounting, derived-state recompute signals, manual overrides, coverage
// facts, and audit-transition retention. It is composed into the top-level
// store.PostgresStore via embedding so callers keep a single store handle.
//
// The single-table account_states / account_state_transitions statements are
// generated by sqlc (see internal/store/account/queries and the accountdb
// sub-package). The exported methods below stay the public surface and keep
// owning transaction orchestration and pubkey normalization; they call the
// generated statements through a *accountdb.Queries bound to the pool or an
// in-flight pgx.Tx. Two statements stay hand-written: the multi-array
// observation upsert (sqlc cannot analyze multi-column unnest) and the
// cross-context signals join (it reaches into the trust and profile
// projections, outside this context's schema).
package account

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/xdzczk/nostrmash/internal/store/account/accountdb"
)

// Store is the account-state data-access surface backed by a shared pool.
type Accounts struct {
	pool *pgxpool.Pool
}

// New builds an account Store over the shared connection pool.
func New(pool *pgxpool.Pool) *Accounts {
	return &Accounts{pool: pool}
}

// AccountStateRow is the full persisted account-state record, including
// coverage/completeness fields.
type AccountStateRow struct {
	Pubkey                    string
	State                     string
	DerivedState              string
	ManualOverride            *string
	FirstSeenAt               time.Time
	FirstTrackedAt            *time.Time
	LastObservedAt            time.Time
	ObservedCount             int64
	LastHydratedAt            *time.Time
	LastSuccessfulHydrationAt *time.Time
	OldestKnownNoteAt         *time.Time
	NewestKnownNoteAt         *time.Time
	EngagementLastCheckedAt   *time.Time
	CoverageWindowDays        *int
	UpdatedAt                 time.Time
	DerivationVersion         int64
	Exists                    bool
}

// AccountSignalRow carries the cheap signals used to recompute an account's
// derived state, plus the current persisted state for change detection.
type AccountSignalRow struct {
	Pubkey         string
	TrustHops      int // -1 when not in trust graph
	ObservedCount  int64
	HasProfile     bool
	NoteCount      int
	CurrentState   string
	CurrentDerived string
	ManualOverride *string
	Tracked        bool // first_tracked_at IS NOT NULL
}

// BatchIncrementAccountObservations records that each pubkey was observed an
// additional N times. New pubkeys get an account_states row in the default
// 'unknown' state. This is the counts-only observation accounting that feeds
// signal-driven promotion without retaining raw payloads.
//
// Hand-written (not sqlc): the multi-column unnest($1,$2) upsert cannot be
// statically analyzed by sqlc's query analyzer.
func (s *Accounts) BatchIncrementAccountObservations(ctx context.Context, deltas map[string]int64) error {
	if s == nil || s.pool == nil {
		return fmt.Errorf("store is not initialized")
	}
	if len(deltas) == 0 {
		return nil
	}
	pubkeys := make([]string, 0, len(deltas))
	counts := make([]int64, 0, len(deltas))
	for pubkey, delta := range deltas {
		pubkey = strings.ToLower(strings.TrimSpace(pubkey))
		if pubkey == "" || delta <= 0 {
			continue
		}
		pubkeys = append(pubkeys, pubkey)
		counts = append(counts, delta)
	}
	if len(pubkeys) == 0 {
		return nil
	}
	_, err := s.pool.Exec(ctx, `
		INSERT INTO account_states (pubkey, observed_count, last_observed_at, first_seen_at, updated_at)
		SELECT t.pubkey, t.delta, now(), now(), now()
		FROM unnest($1::text[], $2::bigint[]) AS t(pubkey, delta)
		ON CONFLICT (pubkey) DO UPDATE
		SET observed_count = account_states.observed_count + EXCLUDED.observed_count,
		    last_observed_at = now()
	`, pubkeys, counts)
	if err != nil {
		return fmt.Errorf("batch increment account observations: %w", err)
	}
	return nil
}

// ListAccountSignalsForRecompute returns a batch of account signal rows for the
// derived-state recompute loop. Rows are ordered oldest-updated first so the
// loop naturally revisits stale accounts. When staleBefore is non-zero only
// rows updated before it are returned.
//
// Hand-written (not sqlc): the query joins into the trust and profile
// projections, which live in other bounded contexts and are not part of this
// context's sqlc schema.
func (s *Accounts) ListAccountSignalsForRecompute(ctx context.Context, limit int, staleBefore time.Time) ([]AccountSignalRow, error) {
	if s == nil || s.pool == nil {
		return nil, fmt.Errorf("store is not initialized")
	}
	if limit <= 0 {
		limit = 500
	}
	rows, err := s.pool.Query(ctx, `
		SELECT a.pubkey,
		       COALESCE(g.min_hops, -1) AS trust_hops,
		       a.observed_count,
		       (p.pubkey IS NOT NULL) AS has_profile,
		       COALESCE(ps.note_count, 0) AS note_count,
		       a.state,
		       a.derived_state,
		       a.manual_override,
		       (a.first_tracked_at IS NOT NULL) AS tracked
		FROM account_states a
		LEFT JOIN trust_graph_snapshot g ON g.pubkey = a.pubkey
		LEFT JOIN profiles_latest p ON p.pubkey = a.pubkey
		LEFT JOIN profile_public_stats ps ON ps.pubkey = a.pubkey
		WHERE ($1::timestamptz IS NULL OR a.updated_at < $1)
		ORDER BY a.updated_at ASC
		LIMIT $2
	`, nullableTime(staleBefore), limit)
	if err != nil {
		return nil, fmt.Errorf("list account signals: %w", err)
	}
	defer rows.Close()
	out := make([]AccountSignalRow, 0, limit)
	for rows.Next() {
		var r AccountSignalRow
		if err := rows.Scan(
			&r.Pubkey,
			&r.TrustHops,
			&r.ObservedCount,
			&r.HasProfile,
			&r.NoteCount,
			&r.CurrentState,
			&r.CurrentDerived,
			&r.ManualOverride,
			&r.Tracked,
		); err != nil {
			return nil, fmt.Errorf("scan account signal row: %w", err)
		}
		out = append(out, r)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("read account signal rows: %w", err)
	}
	return out, nil
}

// ApplyAccountState writes the recomputed derived/effective state for a pubkey.
// When the effective state changes it also records an audit transition. The
// update and transition share one transaction.
func (s *Accounts) ApplyAccountState(
	ctx context.Context,
	pubkey string,
	fromState string,
	derived string,
	effective string,
	source string,
	reason string,
) error {
	if s == nil || s.pool == nil {
		return fmt.Errorf("store is not initialized")
	}
	pubkey = strings.ToLower(strings.TrimSpace(pubkey))
	if pubkey == "" {
		return fmt.Errorf("pubkey is required")
	}
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin apply account state: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	q := accountdb.New(tx)
	if err := q.ApplyAccountStateUpdate(ctx, accountdb.ApplyAccountStateUpdateParams{
		DerivedState:   derived,
		EffectiveState: effective,
		Pubkey:         pubkey,
	}); err != nil {
		return fmt.Errorf("update account state: %w", err)
	}
	if effective != fromState {
		if err := insertAccountStateTransition(ctx, tx, pubkey, fromState, effective, source, reason); err != nil {
			return err
		}
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit apply account state: %w", err)
	}
	return nil
}

// SetAccountManualOverride sets (or clears, when override is empty) the manual
// override for an account and recomputes the effective state. A manual override
// always wins over the derived state. Creates the row if missing.
func (s *Accounts) SetAccountManualOverride(ctx context.Context, pubkey string, override string, reason string) (fromState string, err error) {
	if s == nil || s.pool == nil {
		return "", fmt.Errorf("store is not initialized")
	}
	pubkey = strings.ToLower(strings.TrimSpace(pubkey))
	if pubkey == "" {
		return "", fmt.Errorf("pubkey is required")
	}
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return "", fmt.Errorf("begin set override: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	q := accountdb.New(tx)
	var prev string
	var derived string
	row, err := q.GetAccountStateForOverride(ctx, pubkey)
	if err != nil {
		if err != pgx.ErrNoRows {
			return "", fmt.Errorf("load account for override: %w", err)
		}
		prev = "unknown"
		derived = "unknown"
		if err := q.InsertUnknownAccountState(ctx, pubkey); err != nil {
			return "", fmt.Errorf("insert account for override: %w", err)
		}
	} else {
		prev = row.State
		derived = row.DerivedState
	}

	override = strings.ToLower(strings.TrimSpace(override))
	var effective string
	var overrideArg *string
	if override == "" {
		effective = derived
	} else {
		effective = override
		overrideArg = &override
	}
	if err := q.ApplyAccountManualOverride(ctx, accountdb.ApplyAccountManualOverrideParams{
		ManualOverride: overrideArg,
		EffectiveState: effective,
		Pubkey:         pubkey,
	}); err != nil {
		return "", fmt.Errorf("apply override: %w", err)
	}
	if effective != prev {
		if err := insertAccountStateTransition(ctx, tx, pubkey, prev, effective, "manual", reason); err != nil {
			return "", err
		}
	}
	if err := tx.Commit(ctx); err != nil {
		return "", fmt.Errorf("commit set override: %w", err)
	}
	return prev, nil
}

// PromoteAccountToTracked marks an account as tracked (sets first_tracked_at)
// and raises its effective state to at least 'tracked', unless a manual
// override is in force (in which case only first_tracked_at is set). Used by
// the hydration service so the ingest gate accepts the fetched content.
func (s *Accounts) PromoteAccountToTracked(ctx context.Context, pubkey string, reason string) (fromState string, err error) {
	if s == nil || s.pool == nil {
		return "", fmt.Errorf("store is not initialized")
	}
	pubkey = strings.ToLower(strings.TrimSpace(pubkey))
	if pubkey == "" {
		return "", fmt.Errorf("pubkey is required")
	}
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return "", fmt.Errorf("begin promote: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	q := accountdb.New(tx)
	if err := q.InsertTrackedAccountState(ctx, pubkey); err != nil {
		return "", fmt.Errorf("insert account for promote: %w", err)
	}

	row, err := q.GetAccountStateForPromote(ctx, pubkey)
	if err != nil {
		return "", fmt.Errorf("load account for promote: %w", err)
	}
	prev := row.State
	hasOverride := row.HasOverride

	// Set first_tracked_at if not already set. Only raise the effective state
	// to 'tracked' when there is no manual override and the current rank is
	// below tracked.
	if err := q.PromoteAccountToTracked(ctx, pubkey); err != nil {
		return "", fmt.Errorf("promote account: %w", err)
	}

	if !hasOverride && prev != "tracked" && prev != "strategic" {
		if err := insertAccountStateTransition(ctx, tx, pubkey, prev, "tracked", "hydration", reason); err != nil {
			return "", err
		}
	}
	if err := tx.Commit(ctx); err != nil {
		return "", fmt.Errorf("commit promote: %w", err)
	}
	return prev, nil
}

// UpdateAccountCoverage records hydration coverage facts for an account. Nil
// pointers leave the corresponding column unchanged.
func (s *Accounts) UpdateAccountCoverage(
	ctx context.Context,
	pubkey string,
	lastHydratedAt *time.Time,
	lastSuccessfulHydrationAt *time.Time,
	oldestKnownNoteAt *time.Time,
	newestKnownNoteAt *time.Time,
	engagementLastCheckedAt *time.Time,
	coverageWindowDays *int,
) error {
	if s == nil || s.pool == nil {
		return fmt.Errorf("store is not initialized")
	}
	pubkey = strings.ToLower(strings.TrimSpace(pubkey))
	if pubkey == "" {
		return fmt.Errorf("pubkey is required")
	}
	if err := accountdb.New(s.pool).UpdateAccountCoverage(ctx, accountdb.UpdateAccountCoverageParams{
		LastHydratedAt:            timePtrToTS(lastHydratedAt),
		LastSuccessfulHydrationAt: timePtrToTS(lastSuccessfulHydrationAt),
		OldestKnownNoteAt:         timePtrToTS(oldestKnownNoteAt),
		NewestKnownNoteAt:         timePtrToTS(newestKnownNoteAt),
		EngagementLastCheckedAt:   timePtrToTS(engagementLastCheckedAt),
		CoverageWindowDays:        intPtrToInt32Ptr(coverageWindowDays),
		Pubkey:                    pubkey,
	}); err != nil {
		return fmt.Errorf("update account coverage: %w", err)
	}
	return nil
}

// GetAccountState returns the full account-state row. When the pubkey has no
// row, Exists is false and the rest is zero-valued.
func (s *Accounts) GetAccountState(ctx context.Context, pubkey string) (AccountStateRow, error) {
	if s == nil || s.pool == nil {
		return AccountStateRow{}, fmt.Errorf("store is not initialized")
	}
	pubkey = strings.ToLower(strings.TrimSpace(pubkey))
	if pubkey == "" {
		return AccountStateRow{}, fmt.Errorf("pubkey is required")
	}
	m, err := accountdb.New(s.pool).GetAccountState(ctx, pubkey)
	if err != nil {
		if err == pgx.ErrNoRows {
			return AccountStateRow{Pubkey: pubkey, State: "unknown", DerivedState: "unknown", Exists: false}, nil
		}
		return AccountStateRow{}, fmt.Errorf("get account state: %w", err)
	}
	return AccountStateRow{
		Pubkey:                    m.Pubkey,
		State:                     m.State,
		DerivedState:              m.DerivedState,
		ManualOverride:            m.ManualOverride,
		FirstSeenAt:               m.FirstSeenAt.Time,
		FirstTrackedAt:            tsPtr(m.FirstTrackedAt),
		LastObservedAt:            m.LastObservedAt.Time,
		ObservedCount:             m.ObservedCount,
		LastHydratedAt:            tsPtr(m.LastHydratedAt),
		LastSuccessfulHydrationAt: tsPtr(m.LastSuccessfulHydrationAt),
		OldestKnownNoteAt:         tsPtr(m.OldestKnownNoteAt),
		NewestKnownNoteAt:         tsPtr(m.NewestKnownNoteAt),
		EngagementLastCheckedAt:   tsPtr(m.EngagementLastCheckedAt),
		CoverageWindowDays:        int32PtrToIntPtr(m.CoverageWindowDays),
		UpdatedAt:                 m.UpdatedAt.Time,
		DerivationVersion:         m.DerivationVersion,
		Exists:                    true,
	}, nil
}

// LoadIngestAcceptPubkeys returns pubkeys whose account state means the ingest
// gate should accept their authored content (tracked/strategic), in addition to
// graph-trusted authors.
func (s *Accounts) LoadIngestAcceptPubkeys(ctx context.Context) ([]string, error) {
	return s.loadPubkeysByStates(ctx, []string{"tracked", "strategic"})
}

// LoadBlockedPubkeys returns pubkeys explicitly blocked. The ingest gate drops
// all kinds from these authors.
func (s *Accounts) LoadBlockedPubkeys(ctx context.Context) ([]string, error) {
	return s.loadPubkeysByStates(ctx, []string{"blocked"})
}

func (s *Accounts) loadPubkeysByStates(ctx context.Context, states []string) ([]string, error) {
	if s == nil || s.pool == nil {
		return nil, fmt.Errorf("store is not initialized")
	}
	out, err := accountdb.New(s.pool).LoadPubkeysByStates(ctx, states)
	if err != nil {
		return nil, fmt.Errorf("load pubkeys by state: %w", err)
	}
	return out, nil
}

// CountAccountStates returns the number of accounts in each state for metrics.
func (s *Accounts) CountAccountStates(ctx context.Context) (map[string]int64, error) {
	if s == nil || s.pool == nil {
		return nil, fmt.Errorf("store is not initialized")
	}
	rows, err := accountdb.New(s.pool).CountAccountStates(ctx)
	if err != nil {
		return nil, fmt.Errorf("count account states: %w", err)
	}
	out := make(map[string]int64, 8)
	for _, r := range rows {
		out[r.State] = r.Count
	}
	return out, nil
}

// PurgeAccountStateTransitionsOlderThan deletes audit rows older than cutoff,
// bounded by limit. Operational retention; canonical account state is untouched.
func (s *Accounts) PurgeAccountStateTransitionsOlderThan(ctx context.Context, cutoff time.Time, limit int) (int64, error) {
	if s == nil || s.pool == nil {
		return 0, fmt.Errorf("store is not initialized")
	}
	if limit <= 0 {
		limit = 5000
	}
	n, err := accountdb.New(s.pool).PurgeAccountStateTransitionsOlderThan(ctx, accountdb.PurgeAccountStateTransitionsOlderThanParams{
		Cutoff:   pgtype.Timestamptz{Time: cutoff, Valid: true},
		RowLimit: int32(limit),
	})
	if err != nil {
		return 0, fmt.Errorf("purge account state transitions: %w", err)
	}
	return n, nil
}

func insertAccountStateTransition(ctx context.Context, tx pgx.Tx, pubkey, fromState, toState, source, reason string) error {
	var reasonArg *string
	if strings.TrimSpace(reason) != "" {
		reasonArg = &reason
	}
	if err := accountdb.New(tx).InsertAccountStateTransition(ctx, accountdb.InsertAccountStateTransitionParams{
		Pubkey:    pubkey,
		FromState: fromState,
		ToState:   toState,
		Reason:    reasonArg,
		Source:    source,
	}); err != nil {
		return fmt.Errorf("insert account state transition: %w", err)
	}
	return nil
}

func nullableTime(t time.Time) interface{} {
	if t.IsZero() {
		return nil
	}
	return t
}

func tsPtr(t pgtype.Timestamptz) *time.Time {
	if !t.Valid {
		return nil
	}
	v := t.Time
	return &v
}

func timePtrToTS(t *time.Time) pgtype.Timestamptz {
	if t == nil {
		return pgtype.Timestamptz{}
	}
	return pgtype.Timestamptz{Time: *t, Valid: true}
}

func intPtrToInt32Ptr(v *int) *int32 {
	if v == nil {
		return nil
	}
	x := int32(*v)
	return &x
}

func int32PtrToIntPtr(v *int32) *int {
	if v == nil {
		return nil
	}
	x := int(*v)
	return &x
}
